export type AltLink = { label: string; url: string };

export const apps: {
  slug: string;
  name: string;
  description: string;
  longDescription: string;
  link: string;
  altLinks: AltLink[];
  iconUrl: string;
  emoji: string;
  category: string;
  isTop: boolean;
  isNew: boolean;
  version: string;
  size: string;
  updated: string;
  glow: string;
  border: string;
  text: string;
}[] = [
  {
    slug: "capcut",
    name: "CapCut Premium",
    description: "Editor de video con todas las funciones desbloqueadas.",
    longDescription: "CapCut Premium es la versión desbloqueada del popular editor de video de ByteDance. Incluye todas las funciones Pro sin marca de agua, efectos exclusivos, plantillas premium y exportación en alta calidad. Ideal para creadores de contenido que quieren editar como profesionales desde el celular.",
    link: "https://www.mediafire.com/file/6cct8x99npirkil/CapCut+v19.9.0+ULTⓡA+Unlocked.apk/file",
    altLinks: [
      { label: "Opción 2", url: "https://transfer.it/t/T6Ewvbxx1RoK" },
      { label: "Opción 3", url: "https://www.mediafire.com/file/hpu826yzkqn2xke/CapCut_23.0.0_UltraPro.apk/file" },
    ],
    iconUrl: "https://i.postimg.cc/xd5CgB88/82bd819ca10ca7fa4f51e0cd7dba232f.jpg",
    emoji: "🎬",
    category: "Video",
    isTop: true,
    isNew: false,
    version: "19.9.0",
    size: "180 MB",
    updated: "Oct 2026",
    glow: "rgba(250, 204, 21, 0.4)",
    border: "rgba(250, 204, 21, 0.6)",
    text: "#facc15",
  },
  {
    slug: "youtube",
    name: "YouTube Premium",
    description: "Videos sin anuncios y reproducción en segundo plano.",
    longDescription: "YouTube Premium te permite disfrutar de todos los videos sin anuncios, reproducir en segundo plano, descargar videos para verlos sin conexión y acceder a YouTube Music Premium. Todo desbloqueado y listo para usar.",
    link: "https://cloud.androforever.com/Apps/YouTube/YouTube%20Premium%20v21.39.520%20-%20androforever.com.apk",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/BvSZ8Ngg/eca9ac47a486c83541fa5f81159b8349.jpg",
    emoji: "▶️",
    category: "Video",
    isTop: true,
    isNew: false,
    version: "21.39.520",
    size: "120 MB",
    updated: "Oct 2026",
    glow: "rgba(251, 191, 36, 0.4)",
    border: "rgba(251, 191, 36, 0.6)",
    text: "#fbbf24",
  },
  {
    slug: "netflix",
    name: "Netflix Premium",
    description: "Todo el catálogo en máxima calidad 4K.",
    longDescription: "Netflix Premium desbloqueado con todas las funciones: calidad 4K Ultra HD, descargas ilimitadas, sin anuncios y acceso a todo el catálogo. La mejor experiencia de streaming en tu bolsillo.",
    link: "https://cloud.androforever.com/Apps/Netflix/Netflix%20Premium%20v9.84.0%20-%20androforever.com.apk",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/RhkVNBsg/393747d57d29232eaa98b9ecba7c4dca.jpg",
    emoji: "🍿",
    category: "Video",
    isTop: true,
    isNew: false,
    version: "9.84.0",
    size: "45 MB",
    updated: "Oct 2026",
    glow: "rgba(220, 38, 38, 0.4)",
    border: "rgba(220, 38, 38, 0.6)",
    text: "#fca5a5",
  },
  {
    slug: "novastrim",
    name: "Novastrim VIP",
    description: "Streaming y entretenimiento sin límites.",
    longDescription: "Novastrim VIP es una app de streaming con acceso a películas, series y contenido exclusivo. Versión VIP desbloqueada con todas las funciones premium activadas.",
    link: "https://cloud.androforever.com/Apps/Novastrim/Novastrim%20Mod%20v1.52%20-%20androforever.com.apk",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/brQfK03V/unnamed.png",
    emoji: "📺",
    category: "Video",
    isTop: false,
    isNew: false,
    version: "1.52",
    size: "30 MB",
    updated: "Oct 2026",
    glow: "rgba(168, 85, 247, 0.4)",
    border: "rgba(168, 85, 247, 0.6)",
    text: "#d8b4fe",
  },
  {
    slug: "noutube",
    name: "NouTube",
    description: "Cliente ligero para ver videos sin anuncios.",
    longDescription: "NouTube es un cliente no oficial y ligero para ver videos sin anuncios. Permite reproducción en segundo plano, soporte para descargas y una interfaz limpia y rápida. Ideal para quienes quieren ver sus videos favoritos sin depender de la app oficial.",
    link: "https://www.mediafire.com/file/iimuandwwp2ca2n/noutube-0-6-10.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/442b0659-f99a-40e5-816c-e813b61ba7a9.jpg",
    emoji: "🎼",
    category: "Video",
    isTop: false,
    isNew: true,
    version: "0.6.10",
    size: "15 MB",
    updated: "Oct 2026",
    glow: "rgba(239, 68, 68, 0.4)",
    border: "rgba(239, 68, 68, 0.6)",
    text: "#fca5a5",
  },
  {
    slug: "film-app",
    name: "Film App",
    description: "Películas y series gratis en HD desde tu celular.",
    longDescription: "Film App es una aplicación de streaming con un catálogo enorme de películas y series en alta calidad. Incluye estrenos, clásicos, contenido en HD y 4K, subtítulos en español y la posibilidad de ver sin conexión. Todo desbloqueado y sin anuncios molestos. La mejor alternativa para ver cine desde tu dispositivo.",
    link: "https://www.mediafire.com/file/u8em2j3bqz9uis8/Film_App_v5.0.6.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/fbaeb30e-6ad5-495d-9002-4898760ec929.webp",
    emoji: "🎥",
    category: "Video",
    isTop: false,
    isNew: true,
    version: "5.0.6",
    size: "40 MB",
    updated: "Oct 2026",
    glow: "rgba(220, 38, 38, 0.4)",
    border: "rgba(220, 38, 38, 0.6)",
    text: "#fca5a5",
  },
  {
    slug: "hittv",
    name: "HiTV",
    description: "TV en vivo, películas y series gratis desde tu celular.",
    longDescription: "HiTV es una app de streaming con acceso a canales de TV en vivo de todo el mundo, películas, series, deportes y contenido bajo demanda. Incluye calidad HD, subtítulos en español y una interfaz intuitiva. Todo desbloqueado y sin anuncios molestos. La mejor forma de ver TV desde cualquier lugar.",
    link: "https://www.mediafire.com/file/779gdm3a31xuq05/HiTV_3.13.2_[Mod].apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/edbe52e7-a9fc-4e09-b7ee-0dc65fe103d3/837f6b34-57b2-4e54-8f1c-8aaaf588278e.jpg",
    emoji: "📡",
    category: "Video",
    isTop: false,
    isNew: true,
    version: "3.13.2",
    size: "35 MB",
    updated: "Oct 2026",
    glow: "rgba(249, 115, 22, 0.4)",
    border: "rgba(249, 115, 22, 0.6)",
    text: "#fdba74",
  },
  {
    slug: "inshot",
    name: "InShot Premium",
    description: "Editor de video y fotos con todas las funciones Pro.",
    longDescription: "InShot Premium es uno de los editores de video más populares para Android. Incluye todas las funciones Pro desbloqueadas: sin marca de agua, sin anuncios, efectos exclusivos, transiciones, música, stickers y exportación en alta calidad. Perfecta para creadores de contenido en redes sociales.",
    link: "https://www.mediafire.com/file/r98yth9f76g0wky/InShot_2.850.1815_[Mod].apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/edbe52e7-a9fc-4e09-b7ee-0dc65fe103d3/353ba456-8e8d-4b09-a0ee-f404a00fa213.jpg",
    emoji: "🎞️",
    category: "Video",
    isTop: false,
    isNew: true,
    version: "2.850.1815",
    size: "95 MB",
    updated: "Oct 2026",
    glow: "rgba(239, 68, 68, 0.4)",
    border: "rgba(239, 68, 68, 0.6)",
    text: "#fca5a5",
  },
  {
    slug: "alight-motion",
    name: "Alight Motion Premium",
    description: "Editor de video y animación profesional en tu celular.",
    longDescription: "Alight Motion Premium es la versión desbloqueada de uno de los editores de video y animación más potentes para Android. Incluye todas las funciones Pro sin marca de agua, sin anuncios, con capas ilimitadas, animaciones avanzadas con keyframes, curvas de velocidad, efectos visuales profesionales, soporte para gráficos vectoriales y exportación en alta calidad. Perfecta para editores avanzados y creadores de contenido que quieren efectos únicos.",
    link: "https://www.mediafire.com/file/hipa78efhnkbp59/Alight_Motion_Mod-v5.0.281.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/1bcde049-7a5c-402a-bf6f-5b5cbca3092d/4712561d-91e8-4582-b435-dc6a8bf91209.webp",
    emoji: "🎞️",
    category: "Video",
    isTop: false,
    isNew: true,
    version: "5.0.281",
    size: "85 MB",
    updated: "Oct 2026",
    glow: "rgba(139, 92, 246, 0.4)",
    border: "rgba(139, 92, 246, 0.6)",
    text: "#c4b5fd",
  },
  {
    slug: "wink",
    name: "Wink Premium",
    description: "Edita y mejora tus videos con herramientas profesionales de belleza.",
    longDescription: "Wink Premium es la versión desbloqueada de una de las apps de edición de video más populares para retratos y belleza. Incluye todas las funciones VIP: sin anuncios, sin marca de agua, retoque facial avanzado, moldeado corporal 3D, filtros exclusivos, subtítulos automáticos y exportación en alta calidad. Perfecta para creadores de contenido que quieren lucir perfectos en cada video.",
    link: "https://www.mediafire.com/file/mw4odrrr6isxlvd/WinkMod.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/1bcde049-7a5c-402a-bf6f-5b5cbca3092d/e5ced687-7fbc-4b03-bb6a-e7df90343d0f.webp",
    emoji: "✨",
    category: "Video",
    isTop: false,
    isNew: true,
    version: "2.27.0",
    size: "70 MB",
    updated: "Oct 2026",
    glow: "rgba(236, 72, 153, 0.4)",
    border: "rgba(236, 72, 153, 0.6)",
    text: "#f9a8d4",
  },
  {
    slug: "spotify",
    name: "Spotify Premium",
    description: "Música sin anuncios y descargas offline.",
    longDescription: "Spotify Premium desbloqueado con todas las funciones: música sin anuncios, saltos ilimitados, descargas offline, calidad de audio extrema y reproducción de cualquier canción sin restricciones.",
    link: "https://www.mediafire.com/file/lwujnt40rg2iwe8/Spotify_v9.1.88.2204_MOD_mundoperfecto.net.apk/file",
    altLinks: [
      { label: "Opción 2", url: "https://www.mediafire.com/file/o3owv3cvz0qyxwb/Spotify_pro_x4x_.apk/file" },
    ],
    iconUrl: "https://i.postimg.cc/8PmV4HFL/IMG-20261001-WA0162(1).jpg",
    emoji: "🎧",
    category: "Música",
    isTop: true,
    isNew: false,
    version: "9.1.88.2204",
    size: "135 MB",
    updated: "Oct 2026",
    glow: "rgba(34, 197, 94, 0.4)",
    border: "rgba(34, 197, 94, 0.6)",
    text: "#86efac",
  },
  {
    slug: "youtube-music",
    name: "YouTube Music Premium",
    description: "Tu música favorita sin interrupciones.",
    longDescription: "YouTube Music Premium con todas las funciones desbloqueadas: sin anuncios, reproducción en segundo plano, descargas offline y acceso ilimitado a todo el catálogo musical.",
    link: "https://recordapk.com/youtube-music-mod-apk/download/0/",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/vZLHHCWQ/03b22a2d5bba9d8fa2ac503b30d3b216.jpg",
    emoji: "🎵",
    category: "Música",
    isTop: false,
    isNew: false,
    version: "7.10.0",
    size: "60 MB",
    updated: "Oct 2026",
    glow: "rgba(244, 63, 94, 0.4)",
    border: "rgba(244, 63, 94, 0.6)",
    text: "#fda4af",
  },
  {
    slug: "echo-music",
    name: "Echo Music",
    description: "Descubre nuevos sonidos y artistas sin límites.",
    longDescription: "Echo Music es un reproductor de música con acceso ilimitado a canciones, artistas y playlists. Sin anuncios, sin restricciones y con la mejor calidad de audio.",
    link: "https://github.com/EchoMusicApp/Echo-Music/releases/download/v1.2.6/EchoMusic.apk",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/htBXYpPL/images.png",
    emoji: "🔊",
    category: "Música",
    isTop: false,
    isNew: true,
    version: "1.2.6",
    size: "20 MB",
    updated: "Oct 2026",
    glow: "rgba(236, 72, 153, 0.4)",
    border: "rgba(236, 72, 153, 0.6)",
    text: "#f9a8d4",
  },
  {
    slug: "soundcloud",
    name: "SoundCloud Premium",
    description: "Millones de canciones y podcasts sin anuncios.",
    longDescription: "SoundCloud Premium desbloqueado con todas las funciones: escucha millones de canciones, remixes, podcasts y sets de DJ sin anuncios. Descarga música para escuchar offline, salta canciones sin límite y accede a contenido exclusivo de artistas independientes. La plataforma favorita de los amantes de la música alternativa y underground.",
    link: "https://cloud.androforever.com/Apps/SoundCloud/SoundCloud%20Premium%20v2026.09.23%20-%20androforever.com.apk",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/QM8Nb4kX/29e68872e86c703b6de54c379e2044e2.jpg",
    emoji: "☁️",
    category: "Música",
    isTop: false,
    isNew: true,
    version: "2026.09.23",
    size: "40 MB",
    updated: "Oct 2026",
    glow: "rgba(255, 85, 0, 0.4)",
    border: "rgba(255, 85, 0, 0.6)",
    text: "#fdba74",
  },
  {
    slug: "telegram",
    name: "Telegram Premium",
    description: "Mensajería rápida, segura y sin límites.",
    longDescription: "Telegram Premium con todas las funciones desbloqueadas: sin límites de subida, stickers exclusivos, velocidad de descarga mejorada, reacciones personalizadas y mucho más.",
    link: "https://cloud.androforever.com/Apps/Telegram/Telegram%20Premium%20v12.10.6%20-%20androforever.com.apk",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/9XKfxdmy/2952b7f67446895f8f11c3afacc89edc.jpg",
    emoji: "✈️",
    category: "Social",
    isTop: true,
    isNew: false,
    version: "12.10.6",
    size: "70 MB",
    updated: "Oct 2026",
    glow: "rgba(14, 165, 233, 0.4)",
    border: "rgba(14, 165, 233, 0.6)",
    text: "#7dd3fc",
  },
  {
    slug: "tiktok-gold",
    name: "TikTok Gold",
    description: "TikTok sin anuncios, sin marca de agua y con todas las funciones.",
    longDescription: "TikTok Gold es la versión modificada de TikTok con todas las funciones premium desbloqueadas: sin anuncios, descarga de videos sin marca de agua, región desbloqueada, temas personalizados y acceso a contenido restringido. La mejor forma de disfrutar TikTok al máximo.",
    link: "https://www.mediafire.com/file/c9dh59dj9ptemg9/TikTok_Gold_v4.95.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/77897f29-75c7-48c2-8759-aa1114d304a8.jpg",
    emoji: "🎵",
    category: "Social",
    isTop: false,
    isNew: true,
    version: "4.95",
    size: "180 MB",
    updated: "Oct 2026",
    glow: "rgba(236, 72, 153, 0.4)",
    border: "rgba(236, 72, 153, 0.6)",
    text: "#f9a8d4",
  },
  {
    slug: "instagram",
    name: "Instagram Premium",
    description: "Instagram sin anuncios, con descargas y funciones extra.",
    longDescription: "InstaZen (Instagram Premium) es la versión modificada de Instagram con todas las funciones desbloqueadas: sin anuncios, descarga de fotos, videos e historias, sin marca de visto, temas oscuros personalizados y acceso a funciones exclusivas. Clon independiente para que puedas tener Instagram normal y Premium al mismo tiempo.",
    link: "https://www.mediafire.com/file/pawgtmzx2xe8404/InstaZen_V8.5_%255B64_BIT_CLONE%255D_%2540TUTOSCONNANU_2026.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/5826d90c-4ba9-4083-9782-2a646d60f1ca.jpg",
    emoji: "📷",
    category: "Social",
    isTop: false,
    isNew: true,
    version: "8.5",
    size: "90 MB",
    updated: "Oct 2026",
    glow: "rgba(236, 72, 153, 0.4)",
    border: "rgba(236, 72, 153, 0.6)",
    text: "#f9a8d4",
  },
  {
    slug: "xuper",
    name: "Xuper Premium",
    description: "La app definitiva para ver TV y contenido en streaming.",
    longDescription: "Xuper Premium es una app todo-en-uno con funciones exclusivas para ver TV, deportes y contenido en streaming. Versión Premium desbloqueada con todas las ventajas activadas. Disponible en dos versiones: para celular y para TV, elige la que mejor se adapte a tu dispositivo.",
    link: "https://cloud.androforever.com/Apps/Xuper%20TV/Xuper%20Premium%20v5.0.6%20para%20cel%20-%20androforever.com.apk",
    altLinks: [
      { label: "Versión para TV", url: "https://cloud.androforever.com/Apps/Xuper%20TV/Xuper%20Premium%20v5.0.6%20para%20TV%20-%20androforever.com.apk" },
    ],
    iconUrl: "https://i.postimg.cc/qR50dMsD/IMG-20260930-WA0437.jpg",
    emoji: "⚡",
    category: "Herramientas",
    isTop: false,
    isNew: true,
    version: "5.0.6",
    size: "25 MB",
    updated: "Oct 2026",
    glow: "rgba(249, 115, 22, 0.4)",
    border: "rgba(249, 115, 22, 0.6)",
    text: "#fdba74",
  },
  {
    slug: "microg",
    name: "MicroG",
    description: "Servicios de Google optimizados y ligeros.",
    longDescription: "MicroG es una implementación libre y ligera de los servicios de Google. Perfecta para dispositivos sin Google Play Services o para quienes buscan una alternativa más rápida y con menos consumo de batería.",
    link: "https://cloud.androforever.com/Apps/MicroG/microg-7.1.1.apk",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/Jh8zTnxQ/images.jpg",
    emoji: "🤖",
    category: "Herramientas",
    isTop: false,
    isNew: true,
    version: "7.1.1",
    size: "15 MB",
    updated: "Oct 2026",
    glow: "rgba(20, 184, 166, 0.4)",
    border: "rgba(20, 184, 166, 0.6)",
    text: "#5eead4",
  },
  {
    slug: "remini",
    name: "Remini Premium",
    description: "Mejora la calidad de tus fotos con inteligencia artificial.",
    longDescription: "Remini Premium usa inteligencia artificial para mejorar la calidad de tus fotos antiguas, borrosas o de baja resolución. Convierte fotos pixeladas en imágenes nítidas y de alta definición, restaura rostros, mejora selfies y da vida nueva a tus recuerdos. Sin anuncios, sin marca de agua y con todas las funciones premium desbloqueadas.",
    link: "https://www.mediafire.com/file/u93qnz6iyrnn7vx/Remini_3.7.1447_[Mod].apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/edbe52e7-a9fc-4e09-b7ee-0dc65fe103d3/9d2e7f40-7dd3-46af-be50-89df04762305.jpg",
    emoji: "✨",
    category: "Herramientas",
    isTop: false,
    isNew: true,
    version: "3.7.1447",
    size: "105 MB",
    updated: "Oct 2026",
    glow: "rgba(236, 72, 153, 0.4)",
    border: "rgba(236, 72, 153, 0.6)",
    text: "#f9a8d4",
  },
  {
    slug: "duolingo",
    name: "Duolingo Premium",
    description: "Aprende idiomas gratis y sin anuncios.",
    longDescription: "Duolingo Premium desbloqueado con todas las funciones: sin anuncios, vidas ilimitadas, práctica ilimitada y acceso completo a todos los idiomas. La forma más divertida de aprender inglés, francés, alemán, portugués y más de 30 idiomas desde tu celular.",
    link: "https://cloud.androforever.com/Apps/Duolingo/Duolingo%20Premium%20v6.99.2%20-%20androforever.com.apk",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/pdCSnWdr/4105191f477117656fbe269169a264ca.jpg",
    emoji: "🦉",
    category: "Educación",
    isTop: false,
    isNew: true,
    version: "6.99.2",
    size: "60 MB",
    updated: "Oct 2026",
    glow: "rgba(88, 204, 2, 0.4)",
    border: "rgba(88, 204, 2, 0.6)",
    text: "#a3e635",
  },
  {
    slug: "ibispaint",
    name: "ibisPaint X Premium",
    description: "Dibuja y pinta como profesional en tu celular.",
    longDescription: "ibisPaint X Premium es una de las mejores apps de dibujo para Android. Incluye todas las funciones premium desbloqueadas: pinceles exclusivos, sin anuncios, capas ilimitadas, filtros avanzados y herramientas de dibujo profesional. Perfecta para artistas digitales, ilustradores y aficionados al dibujo.",
    link: "https://cloud.androforever.com/Apps/ibis%20Paint%20X/ibisPaint%20X%20Premium%20v14.1.2_Fixed%20-%20androforever.com.apk",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/7hFtybBx/290aa376610440427eb511c5ed0c91b3.jpg",
    emoji: "🎨",
    category: "Herramientas",
    isTop: false,
    isNew: true,
    version: "14.1.2",
    size: "35 MB",
    updated: "Oct 2026",
    glow: "rgba(236, 72, 153, 0.4)",
    border: "rgba(236, 72, 153, 0.6)",
    text: "#f9a8d4",
  },
  {
    slug: "picsart",
    name: "PicsArt Premium",
    description: "Edita fotos y crea diseños como un profesional.",
    longDescription: "PicsArt Premium es la versión desbloqueada de uno de los editores de fotos más populares del mundo. Incluye todas las funciones premium: sin anuncios, sin marca de agua, efectos exclusivos, stickers, fuentes, plantillas y herramientas de IA. Perfecta para crear contenido visual de calidad desde tu celular.",
    link: "https://www.mediafire.com/file/9rdnmp3agaj3pet/base.apk/file",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/QxBqrpKS/82435a053d8de687f25337fcf5a5d9da.jpg",
    emoji: "📸",
    category: "Herramientas",
    isTop: false,
    isNew: true,
    version: "26.0.0",
    size: "80 MB",
    updated: "Oct 2026",
    glow: "rgba(168, 85, 247, 0.4)",
    border: "rgba(168, 85, 247, 0.6)",
    text: "#d8b4fe",
  },
  {
    slug: "background-eraser",
    name: "Background Eraser Pro",
    description: "Elimina fondos de fotos con IA en segundos.",
    longDescription: "Background Eraser Pro es la herramienta definitiva para eliminar fondos de imágenes con inteligencia artificial. Incluye modo automático de un toque, modo manual para recortes precisos, generador de fondos con IA, creación de avatares, eliminación de objetos no deseados y mucho más. Perfecta para crear stickers, fotos de perfil y contenido profesional.",
    link: "https://www.mediafire.com/file/y562rh3ak7myy8t/Background+Eraser+PRO.apk/file",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/FR0SLn9d/104cca4c60b10afe31eb6e58de5c8812.jpg",
    emoji: "🖼️",
    category: "Herramientas",
    isTop: false,
    isNew: true,
    version: "2.331.100",
    size: "45 MB",
    updated: "Oct 2026",
    glow: "rgba(20, 184, 166, 0.4)",
    border: "rgba(20, 184, 166, 0.6)",
    text: "#5eead4",
  },
  {
    slug: "kwgt",
    name: "KWGT Pro (Kustom Widget)",
    description: "Crea widgets personalizados como un diseñador profesional.",
    longDescription: "KWGT Pro es la versión premium de Kustom Widget Maker, la app definitiva para crear widgets personalizados en Android. Incluye cientos de plantillas, animaciones, formas, gráficos, texto dinámico y soporte para cualquier launcher. Personaliza tu pantalla de inicio como nunca antes con widgets únicos y profesionales.",
    link: "https://www.mediafire.com/file/c3kodyupx6dzqb6/Kustom+Widget+v3.82b621115+(PREMIUM)_sdk.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/1518ee85-005e-4a0d-b0d3-30352b795b32.jpg",
    emoji: "🧩",
    category: "Herramientas",
    isTop: false,
    isNew: true,
    version: "3.82b621115",
    size: "25 MB",
    updated: "Oct 2026",
    glow: "rgba(168, 85, 247, 0.4)",
    border: "rgba(168, 85, 247, 0.6)",
    text: "#d8b4fe",
  },
  {
    slug: "smart-launcher",
    name: "Smart Launcher Pro",
    description: "El launcher más inteligente y elegante para Android.",
    longDescription: "Smart Launcher Pro es la versión premium del aclamado launcher que organiza tus apps automáticamente por categorías. Incluye gestos personalizables, temas exclusivos, widgets inteligentes, iconos adaptativos y una interfaz minimalista que cambia tu Android por completo. Rápido, ligero y elegante.",
    link: "https://www.mediafire.com/file/p3tcwgn4idd1wp3/Smart+Launcher+v6.6+build+021+(Premium)_sdk.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/c35e7c87-b56b-4bcf-bc4f-d3986d5cb573.jpg",
    emoji: "🚀",
    category: "Herramientas",
    isTop: false,
    isNew: true,
    version: "6.6 build 021",
    size: "20 MB",
    updated: "Oct 2026",
    glow: "rgba(14, 165, 233, 0.4)",
    border: "rgba(14, 165, 233, 0.6)",
    text: "#7dd3fc",
  },
  {
    slug: "icon-pack-studio",
    name: "Icon Pack Studio",
    description: "Crea tus propios paquetes de iconos personalizados.",
    longDescription: "Icon Pack Studio es la herramienta definitiva para crear paquetes de iconos personalizados sin necesidad de ser diseñador. Aplica formas, colores, fondos, sombras y efectos a todos los iconos de tu launcher de una sola vez. Compatible con Nova, Smart Launcher, Niagara y más. Transforma tu pantalla de inicio con iconos únicos.",
    link: "https://www.mediafire.com/file/y9lzavmw6vv2k4j/Icon+Pack+Studio+v2.4+build+002+Unrestricted+(Patched).apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/3f6e65b3-dc62-4bae-895a-294cc075a044.png",
    emoji: "🎭",
    category: "Herramientas",
    isTop: false,
    isNew: true,
    version: "2.4 build 002",
    size: "30 MB",
    updated: "Oct 2026",
    glow: "rgba(236, 72, 153, 0.4)",
    border: "rgba(236, 72, 153, 0.6)",
    text: "#f9a8d4",
  },
  {
    slug: "panda-mouse",
    name: "Panda Mouse Pro",
    description: "Juega con teclado y mouse en cualquier juego móvil.",
    longDescription: "Panda Mouse Pro es la herramienta definitiva para jugar con teclado y mouse en tus juegos móviles favoritos. Compatible con Free Fire, PUBG Mobile, Call of Duty Mobile, Fortnite y más de 200 juegos. Incluye mapeo personalizado de teclas, sensibilidad ajustable, sin lag y sin root. Convierte tu celular en una consola portátil.",
    link: "https://www.mediafire.com/file/wjk2wd2qulsudlz/Panda+Mouse+Pro+v6.5+(Paid).apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/2604b575-ba1f-491c-8eb6-e6d4e285c8c6.jpg",
    emoji: "🐼",
    category: "Herramientas",
    isTop: false,
    isNew: true,
    version: "6.5",
    size: "35 MB",
    updated: "Oct 2026",
    glow: "rgba(20, 184, 166, 0.4)",
    border: "rgba(20, 184, 166, 0.6)",
    text: "#5eead4",
  },
  {
    slug: "gta-chinatown",
    name: "GTA: Chinatown Wars",
    description: "El clásico de Rockstar en tu bolsillo, mundo abierto y acción.",
    longDescription: "Grand Theft Auto: Chinatown Wars es uno de los juegos más aclamados de Rockstar para dispositivos móviles. Ambientado en Liberty City, controlas a Huang Lee en una historia llena de crimen, drogas y traición. Incluye misiones variadas, minijuegos, mundo abierto explorable y gráficos estilo cel-shading únicos. Versión completa y desbloqueada.",
    link: "https://www.mediafire.com/file/7s4rqnk5xm0tit0/GTA_Chinatown_Wars_-_v4.4.221_%25283115565%2529_-_APK_-_VPR.apk/file",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/B6w2dymM/IMG-20261001-WA1279.jpg",
    emoji: "🎮",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "4.4.221",
    size: "700 MB",
    updated: "Oct 2026",
    glow: "rgba(239, 68, 68, 0.4)",
    border: "rgba(239, 68, 68, 0.6)",
    text: "#fca5a5",
  },
  {
    slug: "gta-san-andreas",
    name: "GTA: San Andreas (Menú Mod)",
    description: "El clásico de mundo abierto con menú de trucos y dinero ilimitado.",
    longDescription: "Grand Theft Auto: San Andreas es uno de los juegos más icónicos de todos los tiempos. Esta versión modificada incluye un menú de trucos (Cleo Menu) con teleportación, vehículos infinitos, dinero ilimitado, misiones desbloqueadas y todas las funciones premium activadas. Regresa a Los Santos con CJ y la banda Grove Street sin límites.",
    link: "https://www.mediafire.com/file/rgmk44wgqo3njoj/gta-sa-2.11.277-mod-menu-5play.apk/file?dkey=50hi0kqfi3e&r=1296",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/v8W7gDBP/7ff691c1d31d0943c555d6826059cfa4.jpg",
    emoji: "🚗",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "2.11.277",
    size: "2.5 GB",
    updated: "Oct 2026",
    glow: "rgba(250, 204, 21, 0.4)",
    border: "rgba(250, 204, 21, 0.6)",
    text: "#facc15",
  },
  {
    slug: "balatro",
    name: "Balatro",
    description: "El juego de cartas roguelike más adictivo del momento.",
    longDescription: "Balatro es un juego de cartas tipo roguelike que mezcla póker con estrategia, mejoras y combos infinitos. Cada partida es única: construye tu mazo, desbloquea comodines, mejora tus cartas y llega lo más lejos posible. Con millones de combinaciones y una dificultad adictiva, es uno de los juegos más aclamados de 2024-2025. Versión completa desbloqueada.",
    link: "https://www.mediafire.com/file/feu9456iazd92oh/Balatro_1.9_%25281.0.1o%2529_1788811082_latestmodapks.com.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/7c1dca00-c9f4-429c-8e45-e61fbad50024.webp",
    emoji: "🃏",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.9 (1.0.1o)",
    size: "72 MB",
    updated: "Oct 2026",
    glow: "rgba(220, 38, 38, 0.4)",
    border: "rgba(220, 38, 38, 0.6)",
    text: "#fca5a5",
  },
  {
    slug: "sonic-all-stars",
    name: "Sonic & SEGA All-Stars Racing",
    description: "Carreras con Sonic, Tails y todo el universo SEGA.",
    longDescription: "Sonic & SEGA All-Stars Racing es un juego de carreras donde compites con los personajes más icónicos de SEGA. Incluye circuitos inspirados en franquicias legendarias, vehículos personalizables, atajos secretos y modos multijugador local y online. Velocidad, diversión y nostalgia en un solo juego.",
    link: "https://www.mediafire.com/file/2pwtdip5753bpex/sonic+y+sega+all+stars.rar/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/89d4903e-5bc7-4e12-8ed3-1a294057c9e2.jpg",
    emoji: "🏎️",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.0.1",
    size: "451 MB",
    updated: "Oct 2026",
    glow: "rgba(59, 130, 246, 0.4)",
    border: "rgba(59, 130, 246, 0.6)",
    text: "#93c5fd",
  },
  {
    slug: "bendy-ink-machine",
    name: "Bendy and the Ink Machine",
    description: "Terror y puzzles en un estudio de animación maldito.",
    longDescription: "Bendy and the Ink Machine es un juego de terror en primera persona con un estilo visual único inspirado en los dibujos animados de los años 30. Explora el estudio Joey Drew, resuelve puzzles, huye de criaturas aterradoras y descubre el oscuro secreto detrás de la tinta. Una experiencia narrativa inquietante que te mantendrá al borde del asiento.",
    link: "https://www.mediafire.com/file/4bcsknbuf6b53qc/Bendy-and-the-Ink-Machine-v1.0.830-Coimobile.com.apk/file?dkey=oxtqicvb29k&r=561",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/8e230bf1-d5f9-4b42-a140-67aa50f46775.jpg",
    emoji: "🖤",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.0.830",
    size: "171 MB",
    updated: "Oct 2026",
    glow: "rgba(107, 114, 128, 0.4)",
    border: "rgba(107, 114, 128, 0.6)",
    text: "#d1d5db",
  },
  {
    slug: "silksong",
    name: "Hollow Knight: Silksong",
    description: "La esperada secuela de Hollow Knight, ahora en móvil.",
    longDescription: "Hollow Knight: Silksong es la secuela del aclamado metroidvania de Team Cherry. Controla a Hornet en un nuevo reino lleno de peligros, jefes desafiantes y secretos por descubrir. Con combate rápido, plataformas precisas y un mundo interconectado enorme, es una experiencia imprescindible para los amantes de los desafíos.",
    link: "https://dl.apkvision.org/hollow-knight-silksong/Silksong-v1.2.0-full-apkvision.apk",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/b6798857-6b83-4c39-8f7a-c2f9f541a463.jpg",
    emoji: "🕷️",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.2.0",
    size: "1.58 GB",
    updated: "Oct 2026",
    glow: "rgba(239, 68, 68, 0.4)",
    border: "rgba(239, 68, 68, 0.6)",
    text: "#fca5a5",
  },
  {
    slug: "hollow-knight",
    name: "Hollow Knight",
    description: "Metroidvania épico con combate desafiante y mundo interconectado.",
    longDescription: "Hollow Knight es un metroidvania de acción y aventura que te sumerge en el reino de Hallownest. Explora cavernas, lucha contra jefes memorables, desbloquea habilidades y descubre los secretos de una civilización olvidada. Con un diseño artístico hermoso y una dificultad desafiante, es considerado uno de los mejores juegos indie de todos los tiempos.",
    link: "https://dl.apkvision.org/hollow-knight-mobile/hollow-knight-mobile-1.5.78.11833-mod-apkvision.apk",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/a297c612-1e34-4ff7-8d40-f9bb02706c87.jpg",
    emoji: "🗡️",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.5.78.11833",
    size: "938 MB",
    updated: "Oct 2026",
    glow: "rgba(59, 130, 246, 0.4)",
    border: "rgba(59, 130, 246, 0.6)",
    text: "#93c5fd",
  },
  {
    slug: "naruto-ultimate-ninja",
    name: "Naruto Ultimate Ninja Storm",
    description: "Combate ninja en 3D con tus personajes favoritos.",
    longDescription: "Naruto Ultimate Ninja Storm trae la acción del anime a tu celular con combates en 3D espectaculares. Controla a Naruto, Sasuke, Sakura y muchos más en batallas llenas de jutsu, transformaciones y ataques especiales. Modo historia, versus y torneos para horas de diversión ninja.",
    link: "https://mediafire.com/file/r2bvp22zqj11huz/naruto%20ultimate%20ninja%20storm%20mod%20v1.1.1%20-%20espacioapk.com.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/df294079-7ec5-4ea4-afda-916fdc828a69.jpg",
    emoji: "🥷",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.1.1",
    size: "723 MB",
    updated: "Oct 2026",
    glow: "rgba(249, 115, 22, 0.4)",
    border: "rgba(249, 115, 22, 0.6)",
    text: "#fdba74",
  },
  {
    slug: "little-nightmares",
    name: "Little Nightmares",
    description: "Terror y puzzles en un mundo retorcido y fascinante.",
    longDescription: "Little Nightmares es un juego de terror y puzzles donde controlas a Six, una niña atrapada en un mundo grotesco lleno de criaturas aterradoras. Escapa del Maw, resuelve puzzles ambientales y descubre los secretos de este universo retorcido. Con un estilo artístico único y una atmósfera inquietante, es una experiencia inolvidable.",
    link: "https://www.mediafire.com/file/xxevvvasnfbwd7d/little-nightmares_144.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/4568a28d-a8e7-49aa-b77f-030b90d01aac.jpg",
    emoji: "🌙",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.4.4",
    size: "1.07 GB",
    updated: "Oct 2026",
    glow: "rgba(168, 85, 247, 0.4)",
    border: "rgba(168, 85, 247, 0.6)",
    text: "#d8b4fe",
  },
  {
    slug: "universal-truck",
    name: "Universal Truck Simulator",
    description: "Simulador de camiones con gráficos realistas y mundo abierto.",
    longDescription: "Universal Truck Simulator es un simulador de camiones con gráficos de alta calidad y un mundo abierto enorme para explorar. Conduce diferentes camiones, transporta cargas, personaliza tu vehículo y recorre carreteras realistas. Con clima dinámico, tráfico y modos de juego variados, es la experiencia de conducción más completa en móvil.",
    link: "https://www.mediafire.com/file/jnujo7e0qqlkigz/com.dualcarbon.universaltrucksimulator_2.3.1.xapk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/07931ed2-d107-4155-a3b9-f2f165357d03.jpg",
    emoji: "🚛",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "2.3.1",
    size: "501 MB",
    updated: "Oct 2026",
    glow: "rgba(34, 197, 94, 0.4)",
    border: "rgba(34, 197, 94, 0.6)",
    text: "#86efac",
  },
  {
    slug: "bob-esponja-bfbb",
    name: "Bob Esponja: BfBB",
    description: "La aventura clásica de Bob Esponja en 3D, completa y desbloqueada.",
    longDescription: "Bob Esponja: Battle for Bikini Bottom es el remake del clásico juego de plataformas en 3D. Controla a Bob Esponja, Patrick y Sandy para detener los planes de Plankton y salvar Fondo de Bikini. Incluye todos los niveles originales, jefes, coleccionables y gráficos mejorados. Versión completa desbloqueada con todo el contenido disponible.",
    link: "https://www.mediafire.com/file/mtsdfb3rqb7awr0/Bob+Esponja+BfBB+-+1.3.1+-+APK+-+VPR.apk/file?dkey=mqn1jndia4c&r=539",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/1bcde049-7a5c-402a-bf6f-5b5cbca3092d/b17e6694-010c-4b49-89a2-f11873332473.jpg",
    emoji: "🧽",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.3.1",
    size: "2.5 GB",
    updated: "Oct 2026",
    glow: "rgba(250, 204, 21, 0.4)",
    border: "rgba(250, 204, 21, 0.6)",
    text: "#facc15",
  },
  {
    slug: "bob-esponja-cosmic-shake",
    name: "Bob Esponja: The Cosmic Shake",
    description: "Aventura interdimensional con Bob Esponja y sus amigos.",
    longDescription: "Bob Esponja: The Cosmic Shake es un juego de plataformas 3D donde Bob Esponja y Patrick viajan por universos alternativos para salvar Fondo de Bikini. Incluye más de 30 trajes desbloqueables, jefes épicos, niveles llenos de acción y un humor característico de la serie. Versión completa y desbloqueada con todo el contenido.",
    link: "https://www.mediafire.com/file/r2gdvvzswaf6ife/Bob+Esponja+The+Cosmic+Shake+-+v1.1.2+-+APKS+-+VPR.apks/file?dkey=4tt18rig8nx&r=690",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/1bcde049-7a5c-402a-bf6f-5b5cbca3092d/0940a5a6-94f2-4c36-9bfd-27487fc70579.jpg",
    emoji: "🌀",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.1.2",
    size: "2.3 GB",
    updated: "Oct 2026",
    glow: "rgba(59, 130, 246, 0.4)",
    border: "rgba(59, 130, 246, 0.6)",
    text: "#93c5fd",
  },
  {
    slug: "fnaf-1",
    name: "Five Nights at Freddy's 1 (Español)",
    description: "El clásico de terror que inició la saga. En español.",
    longDescription: "Five Nights at Freddy's es el juego de terror que revolucionó el género. Trabajas como guardia nocturno en la pizzería Freddy Fazbear's Pizza, donde los animatrónicos cobran vida por la noche. Debes sobrevivir 5 noches usando las cámaras de seguridad y cerrando las puertas en el momento justo. Versión completa en español, con todos los niveles y jumpscares originales.",
    link: "https://www.mediafire.com/file/7nysoswlpi8cm9l/Five%20Nights%20at%20Freddy%C2%B4s%20(Spanish)%20-%20espacioapk.com.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/edbe52e7-a9fc-4e09-b7ee-0dc65fe103d3/045e11a0-3db9-493f-bbf1-3dd203cd3cd2.jpg",
    emoji: "🐻",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "2.0.0",
    size: "100 MB",
    updated: "Oct 2026",
    glow: "rgba(220, 38, 38, 0.4)",
    border: "rgba(220, 38, 38, 0.6)",
    text: "#fca5a5",
  },
  {
    slug: "fnaf-2",
    name: "Five Nights at Freddy's 2",
    description: "Más animatrónicos, más terror, más difícil.",
    longDescription: "Five Nights at Freddy's 2 es la secuela directa del exitoso juego de terror. Esta vez trabajas en una nueva pizzería con animatrónicos más modernos y peligrosos: Toy Freddy, Toy Bonnie, Toy Chica, Mangle y el temible Puppet. Sin puertas que te protejan, solo una linterna y una máscara de Freddy para sobrevivir. Versión completa con todos los niveles.",
    link: "https://www.mediafire.com/file/3uz8v1l567ejuib/fnaf+2+v2.0.7+-+espacioapk.com.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/edbe52e7-a9fc-4e09-b7ee-0dc65fe103d3/2442044c-56db-4a75-b72f-4b1ba0db3e00.jpg",
    emoji: "🐰",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "2.0.7",
    size: "110 MB",
    updated: "Oct 2026",
    glow: "rgba(249, 115, 22, 0.4)",
    border: "rgba(249, 115, 22, 0.6)",
    text: "#fdba74",
  },
  {
    slug: "fnaf-3",
    name: "Five Nights at Freddy's 3",
    description: "El capítulo más oscuro y aterrador de la saga original.",
    longDescription: "Five Nights at Freddy's 3 te lleva 30 años después del cierre de la pizzería original. Ahora trabajas en una atracción de terror llamada 'Fazbear's Fright' donde el único animatrónico es Springtrap, el más peligroso de toda la saga. Usa el sistema de audio, las cámaras y los conductos de ventilación para sobrevivir. Versión completa con todos los minijuegos ocultos.",
    link: "https://www.mediafire.com/file/rzsbnej1v01uanp/fnaf+3+v2.0.3+-+espacioapk.com.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/edbe52e7-a9fc-4e09-b7ee-0dc65fe103d3/2cb1afcb-95a4-4383-ac0d-c05cf66b9743.jpg",
    emoji: "🐤",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "2.0.3",
    size: "110 MB",
    updated: "Oct 2026",
    glow: "rgba(34, 197, 94, 0.4)",
    border: "rgba(34, 197, 94, 0.6)",
    text: "#86efac",
  },
];

export const categorias = ["Todas", "Video", "Música", "Social", "Herramientas", "Educación", "Juegos"];
