export type AltLink = { label: string; url: string };

export const apps: {
  slug: string;
  name: string;
  description: string;
  longDescription: string;
  link: string;
  altLinks: AltLink[];
  iconUrl: string;
  emoji: string;
  category: string;
  isTop: boolean;
  isNew: boolean;
  version: string;
  size: string;
  updated: string;
  glow: string;
  border: string;
  text: string;
}[] = [
  {
    slug: "capcut",
    name: "CapCut Premium",
    description: "Editor de video con todas las funciones desbloqueadas.",
    longDescription: "CapCut Premium es la versión desbloqueada del popular editor de video de ByteDance. Incluye todas las funciones Pro sin marca de agua, efectos exclusivos, plantillas premium y exportación en alta calidad.",
    link: "https://cloud.androforever.com/Apps/CapCut/CapCut%20v19.9.0%20ULT%E2%93%A1A%20Unlocked.apk",
    altLinks: [
      { label: "Opción 2", url: "https://transfer.it/t/T6Ewvbxx1RoK" },
      { label: "Opción 3", url: "https://www.mediafire.com/file/hpu826yzkqn2xke/CapCut_23.0.0_UltraPro.apk/file" },
    ],
    iconUrl: "https://i.postimg.cc/xd5CgB88/82bd819ca10ca7fa4f51e0cd7dba232f.jpg",
    emoji: "🎬",
    category: "Video",
    isTop: true,
    isNew: false,
    version: "19.9.0",
    size: "180 MB",
    updated: "Oct 2026",
    glow: "rgba(250, 204, 21, 0.4)",
    border: "rgba(250, 204, 21, 0.6)",
    text: "#facc15",
  },
  {
    slug: "youtube",
    name: "YouTube Premium",
    description: "Videos sin anuncios y reproducción en segundo plano.",
    longDescription: "YouTube Premium te permite disfrutar de todos los videos sin anuncios, reproducir en segundo plano, descargar videos para verlos sin conexión y acceder a YouTube Music Premium.",
    link: "https://cloud.androforever.com/Apps/YouTube/YouTube%20Premium%20v21.40.161%20-%20androforever.com.apk",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/BvSZ8Ngg/eca9ac47a486c83541fa5f81159b8349.jpg",
    emoji: "▶️",
    category: "Video",
    isTop: true,
    isNew: false,
    version: "21.40.161",
    size: "120 MB",
    updated: "Oct 2026",
    glow: "rgba(251, 191, 36, 0.4)",
    border: "rgba(251, 191, 36, 0.6)",
    text: "#fbbf24",
  },
  {
    slug: "netflix",
    name: "Netflix Premium",
    description: "Todo el catálogo en máxima calidad 4K.",
    longDescription: "Netflix Premium desbloqueado con todas las funciones: calidad 4K Ultra HD, descargas ilimitadas, sin anuncios y acceso a todo el catálogo.",
    link: "https://cloud.androforever.com/Apps/Netflix/Netflix%20Premium%20v9.84.0%20-%20androforever.com.apk",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/RhkVNBsg/393747d57d29232eaa98b9ecba7c4dca.jpg",
    emoji: "🍿",
    category: "Video",
    isTop: true,
    isNew: false,
    version: "9.84.0",
    size: "45 MB",
    updated: "Oct 2026",
    glow: "rgba(220, 38, 38, 0.4)",
    border: "rgba(220, 38, 38, 0.6)",
    text: "#fca5a5",
  },
  {
    slug: "novastrim",
    name: "Novastrim VIP",
    description: "Streaming y entretenimiento sin límites.",
    longDescription: "Novastrim VIP es una app de streaming con acceso a películas, series y contenido exclusivo.",
    link: "https://cloud.androforever.com/Apps/Novastrim/Novastrim%20Mod%20v1.52%20-%20androforever.com.apk",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/brQfK03V/unnamed.png",
    emoji: "📺",
    category: "Video",
    isTop: false,
    isNew: false,
    version: "1.52",
    size: "30 MB",
    updated: "Oct 2026",
    glow: "rgba(168, 85, 247, 0.4)",
    border: "rgba(168, 85, 247, 0.6)",
    text: "#d8b4fe",
  },
  {
    slug: "noutube",
    name: "NouTube",
    description: "Cliente ligero para ver videos sin anuncios.",
    longDescription: "NouTube es un cliente no oficial y ligero para ver videos sin anuncios.",
    link: "https://www.mediafire.com/file/iimuandwwp2ca2n/noutube-0-6-10.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/442b0659-f99a-40e5-816c-e813b61ba7a9.jpg",
    emoji: "🎼",
    category: "Video",
    isTop: false,
    isNew: true,
    version: "0.6.10",
    size: "15 MB",
    updated: "Oct 2026",
    glow: "rgba(239, 68, 68, 0.4)",
    border: "rgba(239, 68, 68, 0.6)",
    text: "#fca5a5",
  },
  {
    slug: "film-app",
    name: "Film App",
    description: "Películas y series gratis en HD desde tu celular.",
    longDescription: "Film App es una aplicación de streaming con un catálogo enorme de películas y series en alta calidad.",
    link: "https://www.mediafire.com/file/u8em2j3bqz9uis8/Film_App_v5.0.6.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/fbaeb30e-6ad5-495d-9002-4898760ec929.webp",
    emoji: "🎥",
    category: "Video",
    isTop: false,
    isNew: true,
    version: "5.0.6",
    size: "40 MB",
    updated: "Oct 2026",
    glow: "rgba(220, 38, 38, 0.4)",
    border: "rgba(220, 38, 38, 0.6)",
    text: "#fca5a5",
  },
  {
    slug: "hittv",
    name: "HiTV",
    description: "TV en vivo, películas y series gratis desde tu celular.",
    longDescription: "HiTV es una app de streaming con acceso a canales de TV en vivo de todo el mundo.",
    link: "https://www.mediafire.com/file/779gdm3a31xuq05/HiTV_3.13.2_[Mod].apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/edbe52e7-a9fc-4e09-b7ee-0dc65fe103d3/837f6b34-57b2-4e54-8f1c-8aaaf588278e.jpg",
    emoji: "📡",
    category: "Video",
    isTop: false,
    isNew: true,
    version: "3.13.2",
    size: "35 MB",
    updated: "Oct 2026",
    glow: "rgba(249, 115, 22, 0.4)",
    border: "rgba(249, 115, 22, 0.6)",
    text: "#fdba74",
  },
  {
    slug: "dramabox",
    name: "DramaBox Premium",
    description: "Dramas cortos, series y contenido exclusivo sin anuncios.",
    longDescription: "DramaBox Premium es la versión desbloqueada de la popular app de dramas cortos. Incluye acceso ilimitado a todos los episodios, sin anuncios, sin esperas y con calidad HD.",
    link: "https://cloud.androforever.com/Apps/DramaBox/DramaBox%20Premium%20v6.9.0%20-%20androforever.com.apk",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/edbe52e7-a9fc-4e09-b7ee-0dc65fe103d3/81409931-3bd1-4fd9-9b7f-306275e52e20.jpg",
    emoji: "🎭",
    category: "Video",
    isTop: false,
    isNew: true,
    version: "6.9.0",
    size: "50 MB",
    updated: "Oct 2026",
    glow: "rgba(236, 72, 153, 0.4)",
    border: "rgba(236, 72, 153, 0.6)",
    text: "#f9a8d4",
  },
  {
    slug: "inshot",
    name: "InShot Premium",
    description: "Editor de video y fotos con todas las funciones Pro.",
    longDescription: "InShot Premium es uno de los editores de video más populares para Android.",
    link: "https://www.mediafire.com/file/r98yth9f76g0wky/InShot_2.850.1815_[Mod].apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/edbe52e7-a9fc-4e09-b7ee-0dc65fe103d3/353ba456-8e8d-4b09-a0ee-f404a00fa213.jpg",
    emoji: "🎞️",
    category: "Video",
    isTop: false,
    isNew: true,
    version: "2.850.1815",
    size: "95 MB",
    updated: "Oct 2026",
    glow: "rgba(239, 68, 68, 0.4)",
    border: "rgba(239, 68, 68, 0.6)",
    text: "#fca5a5",
  },
  {
    slug: "alight-motion",
    name: "Alight Motion Premium",
    description: "Editor de video y animación profesional en tu celular.",
    longDescription: "Alight Motion Premium es la versión desbloqueada de uno de los editores de video y animación más potentes para Android.",
    link: "https://www.mediafire.com/file/hipa78efhnkbp59/Alight_Motion_Mod-v5.0.281.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/1bcde049-7a5c-402a-bf6f-5b5cbca3092d/4712561d-91e8-4582-b435-dc6a8bf91209.webp",
    emoji: "🎞️",
    category: "Video",
    isTop: false,
    isNew: true,
    version: "5.0.281",
    size: "85 MB",
    updated: "Oct 2026",
    glow: "rgba(139, 92, 246, 0.4)",
    border: "rgba(139, 92, 246, 0.6)",
    text: "#c4b5fd",
  },
  {
    slug: "wink",
    name: "Wink Premium",
    description: "Edita y mejora tus videos con herramientas profesionales de belleza.",
    longDescription: "Wink Premium es la versión desbloqueada de una de las apps de edición de video más populares para retratos y belleza.",
    link: "https://www.mediafire.com/file/mw4odrrr6isxlvd/WinkMod.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/1bcde049-7a5c-402a-bf6f-5b5cbca3092d/e5ced687-7fbc-4b03-bb6a-e7df90343d0f.webp",
    emoji: "✨",
    category: "Video",
    isTop: false,
    isNew: true,
    version: "2.27.0",
    size: "70 MB",
    updated: "Oct 2026",
    glow: "rgba(236, 72, 153, 0.4)",
    border: "rgba(236, 72, 153, 0.6)",
    text: "#f9a8d4",
  },
  {
    slug: "spotify",
    name: "Spotify Premium",
    description: "Música sin anuncios y descargas offline.",
    longDescription: "Spotify Premium desbloqueado con todas las funciones: música sin anuncios, saltos ilimitados, descargas offline y calidad de audio extrema.",
    link: "https://www.mediafire.com/file/lwujnt40rg2iwe8/Spotify_v9.1.88.2204_MOD_mundoperfecto.net.apk/file",
    altLinks: [
      { label: "Opción 2", url: "https://www.mediafire.com/file/o3owv3cvz0qyxwb/Spotify_pro_x4x_.apk/file" },
    ],
    iconUrl: "https://i.postimg.cc/8PmV4HFL/IMG-20261001-WA0162(1).jpg",
    emoji: "🎧",
    category: "Música",
    isTop: true,
    isNew: false,
    version: "9.1.88.2204",
    size: "135 MB",
    updated: "Oct 2026",
    glow: "rgba(34, 197, 94, 0.4)",
    border: "rgba(34, 197, 94, 0.6)",
    text: "#86efac",
  },
  {
    slug: "youtube-music",
    name: "YouTube Music Premium",
    description: "Tu música favorita sin interrupciones.",
    longDescription: "YouTube Music Premium con todas las funciones desbloqueadas: sin anuncios, reproducción en segundo plano, descargas offline.",
    link: "https://recordapk.com/youtube-music-mod-apk/download/0/",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/vZLHHCWQ/03b22a2d5bba9d8fa2ac503b30d3b216.jpg",
    emoji: "🎵",
    category: "Música",
    isTop: false,
    isNew: false,
    version: "7.10.0",
    size: "60 MB",
    updated: "Oct 2026",
    glow: "rgba(244, 63, 94, 0.4)",
    border: "rgba(244, 63, 94, 0.6)",
    text: "#fda4af",
  },
  {
    slug: "echo-music",
    name: "Echo Music",
    description: "Descubre nuevos sonidos y artistas sin límites.",
    longDescription: "Echo Music es un reproductor de música con acceso ilimitado a canciones, artistas y playlists.",
    link: "https://github.com/EchoMusicApp/Echo-Music/releases/download/v1.2.6/EchoMusic.apk",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/htBXYpPL/images.png",
    emoji: "🔊",
    category: "Música",
    isTop: false,
    isNew: true,
    version: "1.2.6",
    size: "20 MB",
    updated: "Oct 2026",
    glow: "rgba(236, 72, 153, 0.4)",
    border: "rgba(236, 72, 153, 0.6)",
    text: "#f9a8d4",
  },
  {
    slug: "soundcloud",
    name: "SoundCloud Premium",
    description: "Millones de canciones y podcasts sin anuncios.",
    longDescription: "SoundCloud Premium desbloqueado con todas las funciones: escucha millones de canciones, remixes, podcasts y sets de DJ sin anuncios.",
    link: "https://cloud.androforever.com/Apps/SoundCloud/SoundCloud%20Premium%20v2026.09.23%20-%20androforever.com.apk",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/QM8Nb4kX/29e68872e86c703b6de54c379e2044e2.jpg",
    emoji: "☁️",
    category: "Música",
    isTop: false,
    isNew: true,
    version: "2026.09.23",
    size: "40 MB",
    updated: "Oct 2026",
    glow: "rgba(255, 85, 0, 0.4)",
    border: "rgba(255, 85, 0, 0.6)",
    text: "#fdba74",
  },
  {
    slug: "telegram",
    name: "Telegram Premium",
    description: "Mensajería rápida, segura y sin límites.",
    longDescription: "Telegram Premium con todas las funciones desbloqueadas: sin límites de subida, stickers exclusivos, velocidad de descarga mejorada.",
    link: "https://cloud.androforever.com/Apps/Telegram/Telegram%20Premium%20v12.10.6%20-%20androforever.com.apk",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/9XKfxdmy/2952b7f67446895f8f11c3afacc89edc.jpg",
    emoji: "✈️",
    category: "Social",
    isTop: true,
    isNew: false,
    version: "12.10.6",
    size: "70 MB",
    updated: "Oct 2026",
    glow: "rgba(14, 165, 233, 0.4)",
    border: "rgba(14, 165, 233, 0.6)",
    text: "#7dd3fc",
  },
  {
    slug: "tiktok-gold",
    name: "TikTok Gold",
    description: "TikTok sin anuncios, sin marca de agua y con todas las funciones.",
    longDescription: "TikTok Gold es la versión modificada de TikTok con todas las funciones premium desbloqueadas: sin anuncios, descarga de videos sin marca de agua.",
    link: "https://www.mediafire.com/file/c9dh59dj9ptemg9/TikTok_Gold_v4.95.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/77897f29-75c7-48c2-8759-aa1114d304a8.jpg",
    emoji: "🎵",
    category: "Social",
    isTop: false,
    isNew: true,
    version: "4.95",
    size: "180 MB",
    updated: "Oct 2026",
    glow: "rgba(236, 72, 153, 0.4)",
    border: "rgba(236, 72, 153, 0.6)",
    text: "#f9a8d4",
  },
  {
    slug: "instagram",
    name: "Instagram Premium",
    description: "Instagram sin anuncios, con descargas y funciones extra.",
    longDescription: "InstaZen (Instagram Premium) es la versión modificada de Instagram con todas las funciones desbloqueadas: sin anuncios, descarga de fotos, videos e historias.",
    link: "https://www.mediafire.com/file/pawgtmzx2xe8404/InstaZen_V8.5_%255B64_BIT_CLONE%255D_%2540TUTOSCONNANU_2026.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/5826d90c-4ba9-4083-9782-2a646d60f1ca.jpg",
    emoji: "📷",
    category: "Social",
    isTop: false,
    isNew: true,
    version: "8.5",
    size: "90 MB",
    updated: "Oct 2026",
    glow: "rgba(236, 72, 153, 0.4)",
    border: "rgba(236, 72, 153, 0.6)",
    text: "#f9a8d4",
  },
  {
    slug: "emochi",
    name: "Emochi Premium",
    description: "Chat con personajes de IA, roleplay y conversaciones sin límites.",
    longDescription: "Emochi Premium es la versión desbloqueada de la popular app de chat con IA. Habla con cientos de personajes virtuales, crea tus propios personajes, ten conversaciones ilimitadas sin anuncios, sin límites de mensajes y con respuestas más rápidas.",
    link: "https://www.mediafire.com/file/ai3ksfto2q5xf77/Emochi-v2.2.13-(Getmodsapk.com)_antisplit.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/edbe52e7-a9fc-4e09-b7ee-0dc65fe103d3/38d8faf4-afc6-4ece-8d18-83596ebc9f6e.jpg",
    emoji: "🎭",
    category: "Social",
    isTop: false,
    isNew: true,
    version: "2.2.13",
    size: "60 MB",
    updated: "Oct 2026",
    glow: "rgba(139, 92, 246, 0.4)",
    border: "rgba(139, 92, 246, 0.6)",
    text: "#c4b5fd",
  },
  {
    slug: "xuper",
    name: "Xuper Premium",
    description: "La app definitiva para ver TV y contenido en streaming.",
    longDescription: "Xuper Premium es una app todo-en-uno con funciones exclusivas para ver TV, deportes y contenido en streaming.",
    link: "https://cloud.androforever.com/Apps/Xuper%20TV/Xuper%20Premium%20v5.0.6%20para%20cel%20-%20androforever.com.apk",
    altLinks: [
      { label: "Versión para TV", url: "https://cloud.androforever.com/Apps/Xuper%20TV/Xuper%20Premium%20v5.0.6%20para%20TV%20-%20androforever.com.apk" },
    ],
    iconUrl: "https://i.postimg.cc/qR50dMsD/IMG-20260930-WA0437.jpg",
    emoji: "⚡",
    category: "Herramientas",
    isTop: false,
    isNew: true,
    version: "5.0.6",
    size: "25 MB",
    updated: "Oct 2026",
    glow: "rgba(249, 115, 22, 0.4)",
    border: "rgba(249, 115, 22, 0.6)",
    text: "#fdba74",
  },
  {
    slug: "sp-ia",
    name: "SP-IA V1",
    description: "Asistente de inteligencia artificial en español, todo en uno.",
    longDescription: "SP-IA V1 es un asistente de inteligencia artificial en español que combina chat, generación de texto, resolución de dudas, traducciones y más. Interfaz simple, respuestas rápidas y sin restricciones.",
    link: "https://www.mediafire.com/file/m7rb6ichbjzl271/sp_ia__beta_.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/edbe52e7-a9fc-4e09-b7ee-0dc65fe103d3/63f7a15c-e6da-47ee-8f27-95fc41619762.png",
    emoji: "🤖",
    category: "Herramientas",
    isTop: false,
    isNew: true,
    version: "1.0",
    size: "30 MB",
    updated: "Oct 2026",
    glow: "rgba(59, 130, 246, 0.4)",
    border: "rgba(59, 130, 246, 0.6)",
    text: "#93c5fd",
  },
  {
    slug: "microg",
    name: "MicroG (Vanced)",
    description: "Servicios de Google optimizados para Vanced y apps modificadas.",
    longDescription: "MicroG Vanced es la versión modificada de los servicios de Google, diseñada específicamente para funcionar con Vanced y otras apps modificadas.",
    link: "https://www.mediafire.com/file/gxngjotn6a9t8uw/vanced.to_vanced_microgre_arm64v8a_v7.2.1-dev.7.apk/file",
    altLinks: [
      { label: "Versión armeabi-v7a (dispositivos antiguos)", url: "https://www.mediafire.com/file/ou8co7eigsgpd68/vanced.to_vanced_microgre_armeabiv7a_v7.2.1-dev.7.apk/file" },
    ],
    iconUrl: "https://i.postimg.cc/Jh8zTnxQ/images.jpg",
    emoji: "🤖",
    category: "Herramientas",
    isTop: false,
    isNew: true,
    version: "7.2.1-dev.7",
    size: "35 MB",
    updated: "Oct 2026",
    glow: "rgba(20, 184, 166, 0.4)",
    border: "rgba(20, 184, 166, 0.6)",
    text: "#5eead4",
  },
  {
    slug: "remini",
    name: "Remini Premium",
    description: "Mejora la calidad de tus fotos con inteligencia artificial.",
    longDescription: "Remini Premium usa inteligencia artificial para mejorar la calidad de tus fotos antiguas, borrosas o de baja resolución.",
    link: "https://www.mediafire.com/file/u93qnz6iyrnn7vx/Remini_3.7.1447_[Mod].apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/edbe52e7-a9fc-4e09-b7ee-0dc65fe103d3/9d2e7f40-7dd3-46af-be50-89df04762305.jpg",
    emoji: "✨",
    category: "Herramientas",
    isTop: false,
    isNew: true,
    version: "3.7.1447",
    size: "105 MB",
    updated: "Oct 2026",
    glow: "rgba(236, 72, 153, 0.4)",
    border: "rgba(236, 72, 153, 0.6)",
    text: "#f9a8d4",
  },
  {
    slug: "duolingo",
    name: "Duolingo Premium",
    description: "Aprende idiomas gratis y sin anuncios.",
    longDescription: "Duolingo Premium desbloqueado con todas las funciones: sin anuncios, vidas ilimitadas, práctica ilimitada y acceso completo a todos los idiomas.",
    link: "https://cloud.androforever.com/Apps/Duolingo/Duolingo%20Premium%20v6.99.2%20-%20androforever.com.apk",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/pdCSnWdr/4105191f477117656fbe269169a264ca.jpg",
    emoji: "🦉",
    category: "Educación",
    isTop: false,
    isNew: true,
    version: "6.99.2",
    size: "60 MB",
    updated: "Oct 2026",
    glow: "rgba(88, 204, 2, 0.4)",
    border: "rgba(88, 204, 2, 0.6)",
    text: "#a3e635",
  },
  {
    slug: "busuu",
    name: "Busuu Premium",
    description: "Aprende idiomas con lecciones interactivas y nativos.",
    longDescription: "Busuu Premium es la versión desbloqueada de una de las apps de idiomas más completas. Incluye todas las lecciones, práctica con hablantes nativos, certificados oficiales y acceso offline sin anuncios.",
    link: "https://cloud.androforever.com/Apps/Busuu/Busuu%20Premium%20v32.48.1%20-%20androforever.com.apk",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/edbe52e7-a9fc-4e09-b7ee-0dc65fe103d3/9bf5a336-d067-4f29-b511-c6162c9fe579.jpg",
    emoji: "📚",
    category: "Educación",
    isTop: false,
    isNew: true,
    version: "32.48.1",
    size: "55 MB",
    updated: "Oct 2026",
    glow: "rgba(139, 92, 246, 0.4)",
    border: "rgba(139, 92, 246, 0.6)",
    text: "#c4b5fd",
  },
  {
    slug: "ibispaint",
    name: "ibisPaint X Premium",
    description: "Dibuja y pinta como profesional en tu celular.",
    longDescription: "ibisPaint X Premium es una de las mejores apps de dibujo para Android.",
    link: "https://cloud.androforever.com/Apps/ibis%20Paint%20X/ibisPaint%20X%20Premium%20v14.1.2_Fixed%20-%20androforever.com.apk",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/7hFtybBx/290aa376610440427eb511c5ed0c91b3.jpg",
    emoji: "🎨",
    category: "Herramientas",
    isTop: false,
    isNew: true,
    version: "14.1.2",
    size: "35 MB",
    updated: "Oct 2026",
    glow: "rgba(236, 72, 153, 0.4)",
    border: "rgba(236, 72, 153, 0.6)",
    text: "#f9a8d4",
  },
  {
    slug: "picsart",
    name: "PicsArt Premium",
    description: "Edita fotos y crea diseños como un profesional.",
    longDescription: "PicsArt Premium es la versión desbloqueada de uno de los editores de fotos más populares del mundo.",
    link: "https://www.mediafire.com/file/9rdnmp3agaj3pet/base.apk/file",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/QxBqrpKS/82435a053d8de687f25337fcf5a5d9da.jpg",
    emoji: "📸",
    category: "Herramientas",
    isTop: false,
    isNew: true,
    version: "26.0.0",
    size: "80 MB",
    updated: "Oct 2026",
    glow: "rgba(168, 85, 247, 0.4)",
    border: "rgba(168, 85, 247, 0.6)",
    text: "#d8b4fe",
  },
  {
    slug: "background-eraser",
    name: "Background Eraser Pro",
    description: "Elimina fondos de fotos con IA en segundos.",
    longDescription: "Background Eraser Pro es la herramienta definitiva para eliminar fondos de imágenes con inteligencia artificial.",
    link: "https://www.mediafire.com/file/y562rh3ak7myy8t/Background+Eraser+PRO.apk/file",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/FR0SLn9d/104cca4c60b10afe31eb6e58de5c8812.jpg",
    emoji: "🖼️",
    category: "Herramientas",
    isTop: false,
    isNew: true,
    version: "2.331.100",
    size: "45 MB",
    updated: "Oct 2026",
    glow: "rgba(20, 184, 166, 0.4)",
    border: "rgba(20, 184, 166, 0.6)",
    text: "#5eead4",
  },
  {
    slug: "kwgt",
    name: "KWGT Pro (Kustom Widget)",
    description: "Crea widgets personalizados como un diseñador profesional.",
    longDescription: "KWGT Pro es la versión premium de Kustom Widget Maker, la app definitiva para crear widgets personalizados en Android.",
    link: "https://www.mediafire.com/file/c3kodyupx6dzqb6/Kustom+Widget+v3.82b621115+(PREMIUM)_sdk.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/1518ee85-005e-4a0d-b0d3-30352b795b32.jpg",
    emoji: "🧩",
    category: "Herramientas",
    isTop: false,
    isNew: true,
    version: "3.82b621115",
    size: "25 MB",
    updated: "Oct 2026",
    glow: "rgba(168, 85, 247, 0.4)",
    border: "rgba(168, 85, 247, 0.6)",
    text: "#d8b4fe",
  },
  {
    slug: "smart-launcher",
    name: "Smart Launcher Pro",
    description: "El launcher más inteligente y elegante para Android.",
    longDescription: "Smart Launcher Pro es la versión premium del aclamado launcher que organiza tus apps automáticamente por categorías.",
    link: "https://www.mediafire.com/file/p3tcwgn4idd1wp3/Smart+Launcher+v6.6+build+021+(Premium)_sdk.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/c35e7c87-b56b-4bcf-bc4f-d3986d5cb573.jpg",
    emoji: "🚀",
    category: "Herramientas",
    isTop: false,
    isNew: true,
    version: "6.6 build 021",
    size: "20 MB",
    updated: "Oct 2026",
    glow: "rgba(14, 165, 233, 0.4)",
    border: "rgba(14, 165, 233, 0.6)",
    text: "#7dd3fc",
  },
  {
    slug: "icon-pack-studio",
    name: "Icon Pack Studio",
    description: "Crea tus propios paquetes de iconos personalizados.",
    longDescription: "Icon Pack Studio es la herramienta definitiva para crear paquetes de iconos personalizados sin necesidad de ser diseñador.",
    link: "https://www.mediafire.com/file/y9lzavmw6vv2k4j/Icon+Pack+Studio+v2.4+build+002+Unrestricted+(Patched).apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/3f6e65b3-dc62-4bae-895a-294cc075a044.png",
    emoji: "🎭",
    category: "Herramientas",
    isTop: false,
    isNew: true,
    version: "2.4 build 002",
    size: "30 MB",
    updated: "Oct 2026",
    glow: "rgba(236, 72, 153, 0.4)",
    border: "rgba(236, 72, 153, 0.6)",
    text: "#f9a8d4",
  },
  {
    slug: "panda-mouse",
    name: "Panda Mouse Pro",
    description: "Juega con teclado y mouse en cualquier juego móvil.",
    longDescription: "Panda Mouse Pro es la herramienta definitiva para jugar con teclado y mouse en tus juegos móviles favoritos.",
    link: "https://www.mediafire.com/file/wjk2wd2qulsudlz/Panda+Mouse+Pro+v6.5+(Paid).apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/2604b575-ba1f-491c-8eb6-e6d4e285c8c6.jpg",
    emoji: "🐼",
    category: "Herramientas",
    isTop: false,
    isNew: true,
    version: "6.5",
    size: "35 MB",
    updated: "Oct 2026",
    glow: "rgba(20, 184, 166, 0.4)",
    border: "rgba(20, 184, 166, 0.6)",
    text: "#5eead4",
  },
  {
    slug: "mcpedl",
    name: "MCPEDL sin Anuncios",
    description: "Descarga mods, mapas y texturas para Minecraft PE sin anuncios.",
    longDescription: "MCPEDL sin Anuncios es la versión modificada de la popular página de mods para Minecraft PE.",
    link: "https://www.mediafire.com/file/t9uu3kn4jhfg5rw/MCPEDL+SIN+ANUNCIOS.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/1bcde049-7a5c-402a-bf6f-5b5cbca3092d/ce6cb7a6-6389-48ee-a70b-94e9fb097cc3.jpg",
    emoji: "⛏️",
    category: "Herramientas",
    isTop: false,
    isNew: true,
    version: "1.0",
    size: "15 MB",
    updated: "Oct 2026",
    glow: "rgba(34, 197, 94, 0.4)",
    border: "rgba(34, 197, 94, 0.6)",
    text: "#86efac",
  },
  {
    slug: "gta-chinatown",
    name: "GTA: Chinatown Wars",
    description: "El clásico de Rockstar en tu bolsillo, mundo abierto y acción.",
    longDescription: "Grand Theft Auto: Chinatown Wars es uno de los juegos más aclamados de Rockstar para dispositivos móviles.",
    link: "https://www.mediafire.com/file/7s4rqnk5xm0tit0/GTA_Chinatown_Wars_-_v4.4.221_%25283115565%2529_-_APK_-_VPR.apk/file",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/B6w2dymM/IMG-20261001-WA1279.jpg",
    emoji: "🎮",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "4.4.221",
    size: "700 MB",
    updated: "Oct 2026",
    glow: "rgba(239, 68, 68, 0.4)",
    border: "rgba(239, 68, 68, 0.6)",
    text: "#fca5a5",
  },
  {
    slug: "gta-san-andreas",
    name: "GTA: San Andreas (Menú Mod)",
    description: "El clásico de mundo abierto con menú de trucos y dinero ilimitado.",
    longDescription: "Grand Theft Auto: San Andreas es uno de los juegos más icónicos de todos los tiempos.",
    link: "https://www.mediafire.com/file/rgmk44wgqo3njoj/gta-sa-2.11.277-mod-menu-5play.apk/file?dkey=50hi0kqfi3e&r=1296",
    altLinks: [],
    iconUrl: "https://i.postimg.cc/v8W7gDBP/7ff691c1d31d0943c555d6826059cfa4.jpg",
    emoji: "🚗",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "2.11.277",
    size: "2.5 GB",
    updated: "Oct 2026",
    glow: "rgba(250, 204, 21, 0.4)",
    border: "rgba(250, 204, 21, 0.6)",
    text: "#facc15",
  },
  {
    slug: "spiderman",
    name: "The Amazing Spider-Man",
    description: "Balanceate por Nueva York como el hombre araña.",
    longDescription: "The Amazing Spider-Man es el juego oficial de la película, con una historia original, combate fluido, balanceo por la ciudad y jefes icónicos. Controla a Peter Parker en su lucha contra el Lagarto y otros villanos en un mundo abierto lleno de acción.",
    link: "https://www.mediafire.com/file/xirodepn95e7xya/Spider-Man+v1.2.3e+Fix.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/1bcde049-7a5c-402a-bf6f-5b5cbca3092d/c8522dc5-09f3-47d5-9829-140b11f3c885.jpg",
    emoji: "🕷️",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.2.3e",
    size: "700 MB",
    updated: "Oct 2026",
    glow: "rgba(220, 38, 38, 0.4)",
    border: "rgba(220, 38, 38, 0.6)",
    text: "#fca5a5",
  },
  {
    slug: "super-mario-64",
    name: "Super Mario 64",
    description: "El clásico 3D de Mario, ahora con mods exclusivos.",
    longDescription: "Super Mario 64 es el juego que definió los plataformas en 3D. Esta versión modificada incluye mejoras gráficas, nuevos modos de juego, personajes extras y controles optimizados para móvil. Salta, corre y vuela por el Castillo de la Princesa Peach.",
    link: "https://www.mediafire.com/file/qlecuueg8fww9dy/Super.Mario64.Mod.agmod.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/1bcde049-7a5c-402a-bf6f-5b5cbca3092d/d776d66f-d4f8-4c15-a3d5-77ecc53f04ff.jpg",
    emoji: "🍄",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "Mod",
    size: "80 MB",
    updated: "Oct 2026",
    glow: "rgba(220, 38, 38, 0.4)",
    border: "rgba(220, 38, 38, 0.6)",
    text: "#fca5a5",
  },
  {
    slug: "celeste",
    name: "Celeste",
    description: "Plataformas de precisión con una historia conmovedora.",
    longDescription: "Celeste es un juego de plataformas de precisión donde controlas a Madeline en su ascenso a la montaña Celeste. Con controles simples, niveles desafiantes y una historia sobre la ansiedad y la superación personal, es considerado uno de los mejores indies de todos los tiempos.",
    link: "https://dl.apkvision.org/celeste/Celeste-v1.0.0-full-apkvision.apk",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/1bcde049-7a5c-402a-bf6f-5b5cbca3092d/f1e07d7d-c535-4a6b-99f6-f1a8377beee2.jpg",
    emoji: "🏔️",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.0.0",
    size: "1.2 GB",
    updated: "Oct 2026",
    glow: "rgba(59, 130, 246, 0.4)",
    border: "rgba(59, 130, 246, 0.6)",
    text: "#93c5fd",
  },
  {
    slug: "human-fall-flat",
    name: "Human Fall Flat",
    description: "Puzzles de física con muñecos gelatinosos, solo o con amigos.",
    longDescription: "Human Fall Flat es un juego de puzzles basado en física donde controlas a un muñeco humanoide gelatinoso a través de niveles oníricos. Solo o con amigos, resuelve acertijos, escala, salta y cae de la forma más divertida. Multijugador online incluido.",
    link: "https://dl.apkvision.org/human-fall-flat/Human-Fall-Flat-v2.6-full-apkvision.apk",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/1bcde049-7a5c-402a-bf6f-5b5cbca3092d/ca5aad5c-cb17-44e7-9a57-29bd547276d3.jpg",
    emoji: "🤸",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "2.6",
    size: "800 MB",
    updated: "Oct 2026",
    glow: "rgba(59, 130, 246, 0.4)",
    border: "rgba(59, 130, 246, 0.6)",
    text: "#93c5fd",
  },
  {
    slug: "hello-neighbor",
    name: "Hello Neighbor",
    description: "Sigilo y terror con un vecino que aprende de ti.",
    longDescription: "Hello Neighbor es un juego de sigilo y terror donde investigas a tu vecino sospechoso. La IA del vecino aprende de tus movimientos y mejora sus trampas cada vez que entras a su casa. Un juego único donde cada partida es diferente.",
    link: "https://files.an1.co/hello-neighbor-mod_2.3.16-an1.com.apk",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/1bcde049-7a5c-402a-bf6f-5b5cbca3092d/e3727aab-0b26-4f70-b37d-cbcdc7744f86.jpg",
    emoji: "🏠",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "2.3.16",
    size: "500 MB",
    updated: "Oct 2026",
    glow: "rgba(249, 115, 22, 0.4)",
    border: "rgba(249, 115, 22, 0.6)",
    text: "#fdba74",
  },
  {
    slug: "cuphead",
    name: "Cuphead (Menú Mod)",
    description: "Run 'n' gun estilo cartoon con jefes brutales.",
    longDescription: "Cuphead es un juego de acción run 'n' gun con un estilo visual inspirado en los dibujos animados de los años 30. Enfréntate a jefes brutales, con música jazz original y con un menú mod que incluye vida infinita, todo desbloqueado y sin daño. El desafío definitivo.",
    link: "https://dl.apkvision.org/cuphead/Cuphead-DLC-v1.0.2-mod-menu-apkvision.apk",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/1bcde049-7a5c-402a-bf6f-5b5cbca3092d/8fdc58b0-cb17-4330-9027-98fdce488088.jpg",
    emoji: "☕",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.0.2",
    size: "1.5 GB",
    updated: "Oct 2026",
    glow: "rgba(220, 38, 38, 0.4)",
    border: "rgba(220, 38, 38, 0.6)",
    text: "#fca5a5",
  },
  {
    slug: "balatro",
    name: "Balatro",
    description: "El juego de cartas roguelike más adictivo del momento.",
    longDescription: "Balatro es un juego de cartas tipo roguelike que mezcla póker con estrategia, mejoras y combos infinitos.",
    link: "https://www.mediafire.com/file/feu9456iazd92oh/Balatro_1.9_%25281.0.1o%2529_1788811082_latestmodapks.com.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/7c1dca00-c9f4-429c-8e45-e61fbad50024.webp",
    emoji: "🃏",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.9 (1.0.1o)",
    size: "72 MB",
    updated: "Oct 2026",
    glow: "rgba(220, 38, 38, 0.4)",
    border: "rgba(220, 38, 38, 0.6)",
    text: "#fca5a5",
  },
  {
    slug: "sonic-all-stars",
    name: "Sonic & SEGA All-Stars Racing",
    description: "Carreras con Sonic, Tails y todo el universo SEGA.",
    longDescription: "Sonic & SEGA All-Stars Racing es un juego de carreras donde compites con los personajes más icónicos de SEGA.",
    link: "https://www.mediafire.com/file/2pwtdip5753bpex/sonic+y+sega+all+stars.rar/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/89d4903e-5bc7-4e12-8ed3-1a294057c9e2.jpg",
    emoji: "🏎️",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.0.1",
    size: "451 MB",
    updated: "Oct 2026",
    glow: "rgba(59, 130, 246, 0.4)",
    border: "rgba(59, 130, 246, 0.6)",
    text: "#93c5fd",
  },
  {
    slug: "bendy-ink-machine",
    name: "Bendy and the Ink Machine",
    description: "Terror y puzzles en un estudio de animación maldito.",
    longDescription: "Bendy and the Ink Machine es un juego de terror en primera persona con un estilo visual único inspirado en los dibujos animados de los años 30.",
    link: "https://www.mediafire.com/file/4bcsknbuf6b53qc/Bendy-and-the-Ink-Machine-v1.0.830-Coimobile.com.apk/file?dkey=oxtqicvb29k&r=561",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/8e230bf1-d5f9-4b42-a140-67aa50f46775.jpg",
    emoji: "🖤",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.0.830",
    size: "171 MB",
    updated: "Oct 2026",
    glow: "rgba(107, 114, 128, 0.4)",
    border: "rgba(107, 114, 128, 0.6)",
    text: "#d1d5db",
  },
  {
    slug: "silksong",
    name: "Hollow Knight: Silksong",
    description: "La esperada secuela de Hollow Knight, ahora en móvil.",
    longDescription: "Hollow Knight: Silksong es la secuela del aclamado metroidvania de Team Cherry.",
    link: "https://dl.apkvision.org/hollow-knight-silksong/Silksong-v1.2.0-full-apkvision.apk",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/b6798857-6b83-4c39-8f7a-c2f9f541a463.jpg",
    emoji: "🕷️",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.2.0",
    size: "1.58 GB",
    updated: "Oct 2026",
    glow: "rgba(239, 68, 68, 0.4)",
    border: "rgba(239, 68, 68, 0.6)",
    text: "#fca5a5",
  },
  {
    slug: "hollow-knight",
    name: "Hollow Knight",
    description: "Metroidvania épico con combate desafiante y mundo interconectado.",
    longDescription: "Hollow Knight es un metroidvania de acción y aventura que te sumerge en el reino de Hallownest.",
    link: "https://dl.apkvision.org/hollow-knight-mobile/hollow-knight-mobile-1.5.78.11833-mod-apkvision.apk",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/a297c612-1e34-4ff7-8d40-f9bb02706c87.jpg",
    emoji: "🗡️",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.5.78.11833",
    size: "938 MB",
    updated: "Oct 2026",
    glow: "rgba(59, 130, 246, 0.4)",
    border: "rgba(59, 130, 246, 0.6)",
    text: "#93c5fd",
  },
  {
    slug: "naruto-ultimate-ninja",
    name: "Naruto Ultimate Ninja Storm",
    description: "Combate ninja en 3D con tus personajes favoritos.",
    longDescription: "Naruto Ultimate Ninja Storm trae la acción del anime a tu celular con combates en 3D espectaculares.",
    link: "https://mediafire.com/file/r2bvp22zqj11huz/naruto%20ultimate%20ninja%20storm%20mod%20v1.1.1%20-%20espacioapk.com.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/df294079-7ec5-4ea4-afda-916fdc828a69.jpg",
    emoji: "🥷",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.1.1",
    size: "723 MB",
    updated: "Oct 2026",
    glow: "rgba(249, 115, 22, 0.4)",
    border: "rgba(249, 115, 22, 0.6)",
    text: "#fdba74",
  },
  {
    slug: "little-nightmares",
    name: "Little Nightmares",
    description: "Terror y puzzles en un mundo retorcido y fascinante.",
    longDescription: "Little Nightmares es un juego de terror y puzzles donde controlas a Six, una niña atrapada en un mundo grotesco.",
    link: "https://www.mediafire.com/file/xxevvvasnfbwd7d/little-nightmares_144.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/4568a28d-a8e7-49aa-b77f-030b90d01aac.jpg",
    emoji: "🌙",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.4.4",
    size: "1.07 GB",
    updated: "Oct 2026",
    glow: "rgba(168, 85, 247, 0.4)",
    border: "rgba(168, 85, 247, 0.6)",
    text: "#d8b4fe",
  },
  {
    slug: "universal-truck",
    name: "Universal Truck Simulator",
    description: "Simulador de camiones con gráficos realistas y mundo abierto.",
    longDescription: "Universal Truck Simulator es un simulador de camiones con gráficos de alta calidad y un mundo abierto enorme para explorar.",
    link: "https://www.mediafire.com/file/jnujo7e0qqlkigz/com.dualcarbon.universaltrucksimulator_2.3.1.xapk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/d029b2d8-a8bd-4326-8d8b-e6be18e9eb7e/07931ed2-d107-4155-a3b9-f2f165357d03.jpg",
    emoji: "🚛",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "2.3.1",
    size: "501 MB",
    updated: "Oct 2026",
    glow: "rgba(34, 197, 94, 0.4)",
    border: "rgba(34, 197, 94, 0.6)",
    text: "#86efac",
  },
  {
    slug: "bob-esponja-bfbb",
    name: "Bob Esponja: BfBB",
    description: "La aventura clásica de Bob Esponja en 3D, completa y desbloqueada.",
    longDescription: "Bob Esponja: Battle for Bikini Bottom es el remake del clásico juego de plataformas en 3D.",
    link: "https://www.mediafire.com/file/mtsdfb3rqb7awr0/Bob+Esponja+BfBB+-+1.3.1+-+APK+-+VPR.apk/file?dkey=mqn1jndia4c&r=539",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/1bcde049-7a5c-402a-bf6f-5b5cbca3092d/b17e6694-010c-4b49-89a2-f11873332473.jpg",
    emoji: "🧽",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.3.1",
    size: "2.5 GB",
    updated: "Oct 2026",
    glow: "rgba(250, 204, 21, 0.4)",
    border: "rgba(250, 204, 21, 0.6)",
    text: "#facc15",
  },
  {
    slug: "bob-esponja-cosmic-shake",
    name: "Bob Esponja: The Cosmic Shake",
    description: "Aventura interdimensional con Bob Esponja y sus amigos.",
    longDescription: "Bob Esponja: The Cosmic Shake es un juego de plataformas 3D donde Bob Esponja y Patrick viajan por universos alternativos.",
    link: "https://www.mediafire.com/file/r2gdvvzswaf6ife/Bob+Esponja+The+Cosmic+Shake+-+v1.1.2+-+APKS+-+VPR.apks/file?dkey=4tt18rig8nx&r=690",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/1bcde049-7a5c-402a-bf6f-5b5cbca3092d/0940a5a6-94f2-4c36-9bfd-27487fc70579.jpg",
    emoji: "🌀",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.1.2",
    size: "2.3 GB",
    updated: "Oct 2026",
    glow: "rgba(59, 130, 246, 0.4)",
    border: "rgba(59, 130, 246, 0.6)",
    text: "#93c5fd",
  },
  {
    slug: "fnaf-1",
    name: "Five Nights at Freddy's 1 (Español)",
    description: "El clásico de terror que inició la saga. En español.",
    longDescription: "Five Nights at Freddy's es el juego de terror que revolucionó el género. Trabajas como guardia nocturno en la pizzería Freddy Fazbear's Pizza.",
    link: "https://www.mediafire.com/file/7nysoswlpi8cm9l/Five%20Nights%20at%20Freddy%C2%B4s%20(Spanish)%20-%20espacioapk.com.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/edbe52e7-a9fc-4e09-b7ee-0dc65fe103d3/e1b31e6d-01ad-4ceb-9369-5d4cd8b31b2e.jpg",
    emoji: "🐻",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "2.0.0",
    size: "100 MB",
    updated: "Oct 2026",
    glow: "rgba(220, 38, 38, 0.4)",
    border: "rgba(220, 38, 38, 0.6)",
    text: "#fca5a5",
  },
  {
    slug: "fnaf-2",
    name: "Five Nights at Freddy's 2",
    description: "Más animatrónicos, más terror, más difícil.",
    longDescription: "Five Nights at Freddy's 2 es la secuela directa del exitoso juego de terror.",
    link: "https://www.mediafire.com/file/3uz8v1l567ejuib/fnaf+2+v2.0.7+-+espacioapk.com.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/edbe52e7-a9fc-4e09-b7ee-0dc65fe103d3/fef2c59a-a766-4a86-a293-aea7643b64bb.jpg",
    emoji: "🐰",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "2.0.7",
    size: "110 MB",
    updated: "Oct 2026",
    glow: "rgba(249, 115, 22, 0.4)",
    border: "rgba(249, 115, 22, 0.6)",
    text: "#fdba74",
  },
  {
    slug: "fnaf-3",
    name: "Five Nights at Freddy's 3",
    description: "El capítulo más oscuro y aterrador de la saga original.",
    longDescription: "Five Nights at Freddy's 3 te lleva 30 años después del cierre de la pizzería original.",
    link: "https://www.mediafire.com/file/rzsbnej1v01uanp/fnaf+3+v2.0.3+-+espacioapk.com.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/edbe52e7-a9fc-4e09-b7ee-0dc65fe103d3/cce93022-beef-406c-a5af-8700a6cb5033.jpg",
    emoji: "🐤",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "2.0.3",
    size: "110 MB",
    updated: "Oct 2026",
    glow: "rgba(34, 197, 94, 0.4)",
    border: "rgba(34, 197, 94, 0.6)",
    text: "#86efac",
  },
  {
    slug: "fnaf-4",
    name: "Five Nights at Freddy's 4",
    description: "El capítulo más terrorífico, ahora en tu habitación.",
    longDescription: "Five Nights at Freddy's 4 es considerado por muchos el capítulo más aterrador de la saga original.",
    link: "https://www.mediafire.com/file/kju6bxorehb3xsy/fnaf_4_v2.0.2_-_espacioapk.com.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/edbe52e7-a9fc-4e09-b7ee-0dc65fe103d3/3808dad5-6711-453b-97d9-87329593e03c.jpg",
    emoji: "👻",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "2.0.2",
    size: "110 MB",
    updated: "Oct 2026",
    glow: "rgba(139, 92, 246, 0.4)",
    border: "rgba(139, 92, 246, 0.6)",
    text: "#c4b5fd",
  },
  {
    slug: "fnaf-6",
    name: "Five Nights at Freddy's 6 (Pizzeria Simulator)",
    description: "Administra tu propia pizzería mientras sobrevives al horror.",
    longDescription: "Five Nights at Freddy's 6: Pizzeria Simulator combina gestión de restaurante con terror puro.",
    link: "https://www.mediafire.com/file/ck8e9x5moh8bpm3/fnaf_6_v1.0.8_-_espacioapk.com.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/edbe52e7-a9fc-4e09-b7ee-0dc65fe103d3/f83082a1-7541-40d6-b79a-f79babd9c8ee.jpg",
    emoji: "🍕",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.0.8",
    size: "150 MB",
    updated: "Oct 2026",
    glow: "rgba(249, 115, 22, 0.4)",
    border: "rgba(249, 115, 22, 0.6)",
    text: "#fdba74",
  },
  {
    slug: "ucn",
    name: "Ultimate Custom Night",
    description: "Crea tu propia noche con más de 50 animatrónicos.",
    longDescription: "Ultimate Custom Night es el juego definitivo para los fans de FNAF.",
    link: "https://www.mediafire.com/file/f97yf8u27m7zmow/ultimate_custom_night_v1.0.6_-_espacioapk.com.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/edbe52e7-a9fc-4e09-b7ee-0dc65fe103d3/db225e73-4088-4379-ad17-e4eb4a6a8ba1.jpg",
    emoji: "🌃",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.0.6",
    size: "130 MB",
    updated: "Oct 2026",
    glow: "rgba(168, 85, 247, 0.4)",
    border: "rgba(168, 85, 247, 0.6)",
    text: "#d8b4fe",
  },
  {
    slug: "poppy-playtime-1",
    name: "Poppy Playtime: Chapter 1",
    description: "El juego de terror con Huggy Wuggy que te hará gritar.",
    longDescription: "Poppy Playtime: Chapter 1 es un juego de terror y puzzles en primera persona donde exploras la abandonada fábrica de juguetes Playtime Co.",
    link: "https://dl.apkvision.org/Poppy-Playtime-Chapter-1/Poppy-Playtime-Chapter-1-v1-0-18-full-apkvision.apk",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/1bcde049-7a5c-402a-bf6f-5b5cbca3092d/dbfa43a3-2b28-46c0-b604-40a5e55f3101.jpg",
    emoji: "🧸",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.0.18",
    size: "800 MB",
    updated: "Oct 2026",
    glow: "rgba(236, 72, 153, 0.4)",
    border: "rgba(236, 72, 153, 0.6)",
    text: "#f9a8d4",
  },
  {
    slug: "poppy-playtime-2",
    name: "Poppy Playtime: Chapter 2",
    description: "Vuelve a Playtime Co. y enfréntate a nuevos horrores.",
    longDescription: "Poppy Playtime: Chapter 2 continúa la historia donde la dejaste.",
    link: "https://dl.apkvision.org/poppy-playtime-chapter-2/Poppy-Playtime-Chapter-2-v1-42-full-apkvision.apk",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/1bcde049-7a5c-402a-bf6f-5b5cbca3092d/7743ac99-f60c-448a-8a77-cb2e3b6c7c1d.jpg",
    emoji: "🕷️",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.42",
    size: "1.2 GB",
    updated: "Oct 2026",
    glow: "rgba(139, 92, 246, 0.4)",
    border: "rgba(139, 92, 246, 0.6)",
    text: "#c4b5fd",
  },
  {
    slug: "poppy-playtime-3",
    name: "Poppy Playtime: Chapter 3",
    description: "El capítulo más terrorífico de la saga hasta ahora.",
    longDescription: "Poppy Playtime: Chapter 3 - Deep Sleep lleva el terror a otro nivel.",
    link: "https://dl.apkvision.org/poppy-playtime-chapter-3/Poppy-Playtime-Chapter-3-v1.0.25-full-apkvision.apk",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/1bcde049-7a5c-402a-bf6f-5b5cbca3092d/8de9f413-9863-4533-9a75-511126a3c07f.jpg",
    emoji: "😱",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.0.25",
    size: "1.5 GB",
    updated: "Oct 2026",
    glow: "rgba(220, 38, 38, 0.4)",
    border: "rgba(220, 38, 38, 0.6)",
    text: "#fca5a5",
  },
  {
    slug: "ppsspp-gold",
    name: "PPSSPP Gold",
    description: "El mejor emulador de PSP para Android, versión Gold desbloqueada.",
    longDescription: "PPSSPP Gold es el emulador de PlayStation Portable más popular y completo para Android.",
    link: "https://www.mediafire.com/file/qdy9ebnhklksy4n/PPSSPP_Gold_PSP_RG%2526AP.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/1bcde049-7a5c-402a-bf6f-5b5cbca3092d/33266d7b-ac61-475b-938c-296ae5e9914c.jpg",
    emoji: "🕹️",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.17.1",
    size: "45 MB",
    updated: "Oct 2026",
    glow: "rgba(250, 204, 21, 0.4)",
    border: "rgba(250, 204, 21, 0.6)",
    text: "#facc15",
  },
  {
    slug: "halo-ce",
    name: "Halo: Combat Evolved",
    description: "El clásico shooter que definió una generación, ahora en Android.",
    longDescription: "Halo: Combat Evolved es el juego que revolucionó los shooters en primera persona. Controla al Jefe Maestro, un supersoldado Spartan, en su misión de defender la humanidad contra la alianza Covenant.",
    link: "https://www.mediafire.com/file/0ld0ea0k9ggwxx7/halo-ce-TheMocs.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/1bcde049-7a5c-402a-bf6f-5b5cbca3092d/7e633a48-2594-41f4-bc5a-0648e0a82fad.jpg",
    emoji: "🛸",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "1.0",
    size: "500 MB",
    updated: "Oct 2026",
    glow: "rgba(34, 197, 94, 0.4)",
    border: "rgba(34, 197, 94, 0.6)",
    text: "#86efac",
  },
  {
    slug: "lovely-craft",
    name: "Lovely Craft: Piston Trap",
    description: "Rompecabezas de física con trampas de pistón y mucha diversión.",
    longDescription: "Lovely Craft: Piston Trap es un adictivo juego de rompecabezas basado en física donde debes usar trampas de pistón para resolver cada nivel.",
    link: "https://www.mediafire.com/file/zf3x5m180ifol77/Lovely%20Craft%20Piston%20Trap%20v0.2.999%20-%20espacioapk.com.apk/file",
    altLinks: [],
    iconUrl: "https://i.supaimg.com/edbe52e7-a9fc-4e09-b7ee-0dc65fe103d3/dcf7f781-4373-4327-b324-c2d38c907c06.webp",
    emoji: "🧩",
    category: "Juegos",
    isTop: false,
    isNew: true,
    version: "0.2.999",
    size: "50 MB",
    updated: "Oct 2026",
    glow: "rgba(59, 130, 246, 0.4)",
    border: "rgba(59, 130, 246, 0.6)",
    text: "#93c5fd",
  },
];

export const categorias = ["Todas", "Video", "Música", "Social", "Herramientas", "Educación", "Juegos"];
