export const apps = [
  { 
    slug: "capcut",
    name: "CapCut Premium", 
    description: "Editor de video con todas las funciones desbloqueadas.", 
    longDescription: "CapCut Premium es la versión desbloqueada del popular editor de video de ByteDance. Incluye todas las funciones Pro sin marca de agua, efectos exclusivos, plantillas premium y exportación en alta calidad. Ideal para creadores de contenido que quieren editar como profesionales desde el celular.",
    link: "https://cloud.androforever.com/Apps/CapCut/CapCut%2019.7.0%20Ultra%20Pro%20-%20androforever.com.apk", 
    iconUrl: "https://i.postimg.cc/xd5CgB88/82bd819ca10ca7fa4f51e0cd7dba232f.jpg", 
    emoji: "🎬", 
    category: "Video", 
    isTop: true, 
    isNew: false, 
    version: "19.7.0", 
    size: "180 MB", 
    updated: "Oct 2026",
    glow: "rgba(250, 204, 21, 0.4)", 
    border: "rgba(250, 204, 21, 0.6)", 
    text: "#facc15" 
  },
  { 
    slug: "youtube",
    name: "YouTube Premium", 
    description: "Videos sin anuncios y reproducción en segundo plano.", 
    longDescription: "YouTube Premium te permite disfrutar de todos los videos sin anuncios, reproducir en segundo plano, descargar videos para verlos sin conexión y acceder a YouTube Music Premium. Todo desbloqueado y listo para usar.",
    link: "https://cloud.androforever.com/Apps/YouTube/YouTube%20Premium%20v21.39.520%20-%20androforever.com.apk", 
    iconUrl: "https://i.postimg.cc/BvSZ8Ngg/eca9ac47a486c83541fa5f81159b8349.jpg", 
    emoji: "▶️", 
    category: "Video", 
    isTop: true, 
    isNew: false, 
    version: "21.39.520", 
    size: "120 MB", 
    updated: "Oct 2026",
    glow: "rgba(251, 191, 36, 0.4)", 
    border: "rgba(251, 191, 36, 0.6)", 
    text: "#fbbf24" 
  },
  { 
    slug: "netflix",
    name: "Netflix Premium", 
    description: "Todo el catálogo en máxima calidad 4K.", 
    longDescription: "Netflix Premium desbloqueado con todas las funciones: calidad 4K Ultra HD, descargas ilimitadas, sin anuncios y acceso a todo el catálogo. La mejor experiencia de streaming en tu bolsillo.",
    link: "https://cloud.androforever.com/Apps/Netflix/Netflix%20Premium%20v9.84.0%20-%20androforever.com.apk", 
    iconUrl: "https://i.postimg.cc/RhkVNBsg/393747d57d29232eaa98b9ecba7c4dca.jpg", 
    emoji: "🍿", 
    category: "Video", 
    isTop: true, 
    isNew: false, 
    version: "9.84.0", 
    size: "45 MB", 
    updated: "Oct 2026",
    glow: "rgba(220, 38, 38, 0.4)", 
    border: "rgba(220, 38, 38, 0.6)", 
    text: "#fca5a5" 
  },
  { 
    slug: "novastrim",
    name: "Novastrim VIP", 
    description: "Streaming y entretenimiento sin límites.", 
    longDescription: "Novastrim VIP es una app de streaming con acceso a películas, series y contenido exclusivo. Versión VIP desbloqueada con todas las funciones premium activadas.",
    link: "https://cloud.androforever.com/Apps/Novastrim/Novastrim%20Mod%20v1.52%20-%20androforever.com.apk", 
    iconUrl: "AQUI_VA_EL_LINK_DE_LA_IMAGEN", 
    emoji: "📺", 
    category: "Video", 
    isTop: false, 
    isNew: false, 
    version: "1.52", 
    size: "30 MB", 
    updated: "Oct 2026",
    glow: "rgba(168, 85, 247, 0.4)", 
    border: "rgba(168, 85, 247, 0.6)", 
    text: "#d8b4fe" 
  },
  { 
    slug: "spotify",
    name: "Spotify Premium", 
    description: "Música sin anuncios y descargas offline.", 
    longDescription: "Spotify Premium desbloqueado con todas las funciones: música sin anuncios, saltos ilimitados, descargas offline, calidad de audio extrema y reproducción de cualquier canción sin restricciones.",
    link: "https://www.mediafire.com/file/3s0cz5sezxhp11k/SpotiWeb_v4.0.0_mundoperfecto.net.apk/file", 
    iconUrl: "https://i.postimg.cc/52M2JfQs/99a0500dc420189ec2fdc984c8493fda.jpg", 
    emoji: "🎧", 
    category: "Música", 
    isTop: true, 
    isNew: false, 
    version: "8.9.0", 
    size: "35 MB", 
    updated: "Oct 2026",
    glow: "rgba(34, 197, 94, 0.4)", 
    border: "rgba(34, 197, 94, 0.6)", 
    text: "#86efac" 
  },
  { 
    slug: "youtube-music",
    name: "YouTube Music Premium", 
    description: "Tu música favorita sin interrupciones.", 
    longDescription: "YouTube Music Premium con todas las funciones desbloqueadas: sin anuncios, reproducción en segundo plano, descargas offline y acceso ilimitado a todo el catálogo musical.",
    link: "https://cloud.androforever.com/Apps/YouTube/YouTube%20Premium%20v21.39.520%20-%20androforever.com.apk", 
    iconUrl: "https://i.postimg.cc/vZLHHCWQ/03b22a2d5bba9d8fa2ac503b30d3b216.jpg", 
    emoji: "🎵", 
    category: "Música", 
    isTop: false, 
    isNew: false, 
    version: "7.10.0", 
    size: "60 MB", 
    updated: "Oct 2026",
    glow: "rgba(244, 63, 94, 0.4)", 
    border: "rgba(244, 63, 94, 0.6)", 
    text: "#fda4af" 
  },
  { 
    slug: "telegram",
    name: "Telegram Premium", 
    description: "Mensajería rápida, segura y sin límites.", 
    longDescription: "Telegram Premium con todas las funciones desbloqueadas: sin límites de subida, stickers exclusivos, velocidad de descarga mejorada, reacciones personalizadas y mucho más.",
    link: "https://cloud.androforever.com/Apps/Telegram/Telegram%20Premium%20v12.10.5%20-%20androforever.com.apk", 
    iconUrl: "https://i.postimg.cc/9XKfxdmy/2952b7f67446895f8f11c3afacc89edc.jpg", 
    emoji: "✈️", 
    category: "Social", 
    isTop: true, 
    isNew: false, 
    version: "12.10.5", 
    size: "70 MB", 
    updated: "Oct 2026",
    glow: "rgba(14, 165, 233, 0.4)", 
    border: "rgba(14, 165, 233, 0.6)", 
    text: "#7dd3fc" 
  },
  { 
    slug: "xuper",
    name: "Xuper Premium", 
    description: "La app definitiva con todas las ventajas.", 
    longDescription: "Xuper Premium es una app todo-en-uno con funciones exclusivas. Versión Premium desbloqueada con todas las ventajas activadas.",
    link: "https://www.mediafire.com/file/gnj9hcs7tiivp1x/XH2.apk/file", 
    iconUrl: "AQUI_VA_EL_LINK_DE_LA_IMAGEN", 
    emoji: "⚡", 
    category: "Herramientas", 
    isTop: false, 
    isNew: true, 
    version: "2.0", 
    size: "25 MB", 
    updated: "Oct 2026",
    glow: "rgba(249, 115, 22, 0.4)", 
    border: "rgba(249, 115, 22, 0.6)", 
    text: "#fdba74" 
  },
  { 
    slug: "microg",
    name: "MicroG", 
    description: "Servicios de Google optimizados y ligeros.", 
    longDescription: "MicroG es una implementación libre y ligera de los servicios de Google. Perfecta para dispositivos sin Google Play Services o para quienes buscan una alternativa más rápida y con menos consumo de batería.",
    link: "https://cloud.androforever.com/Apps/MicroG/microg-7.1.1.apk", 
    iconUrl: "AQUI_VA_EL_LINK_DE_LA_IMAGEN", 
    emoji: "🤖", 
    category: "Herramientas", 
    isTop: false, 
    isNew: true, 
    version: "7.1.1", 
    size: "15 MB", 
    updated: "Oct 2026",
    glow: "rgba(20, 184, 166, 0.4)", 
    border: "rgba(20, 184, 166, 0.6)", 
    text: "#5eead4" 
  },
  { 
    slug: "echo-music",
    name: "Echo Music", 
    description: "Descubre nuevos sonidos y artistas sin límites.", 
    longDescription: "Echo Music es un reproductor de música con acceso ilimitado a canciones, artistas y playlists. Sin anuncios, sin restricciones y con la mejor calidad de audio.",
    link: "https://github.com/EchoMusicApp/Echo-Music/releases/download/v1.2.6/EchoMusic.apk", 
    iconUrl: "AQUI_VA_EL_LINK_DE_LA_IMAGEN", 
    emoji: "🔊", 
    category: "Música", 
    isTop: false, 
    isNew: true, 
    version: "1.2.6", 
    size: "20 MB", 
    updated: "Oct 2026",
    glow: "rgba(236, 72, 153, 0.4)", 
    border: "rgba(236, 72, 153, 0.6)", 
    text: "#f9a8d4" 
  },
];

export const categorias = ["Todas", "Video", "Música", "Social", "Herramientas"];
